insert into materials (id, name, crafted_recipe_id)
values  (1, 'Alcheweed', null),
        (2, 'Amethyst', null),
        (3, 'Ancient Coral', null),
        (4, 'Ancient Core', null),
        (5, 'Ancient Emerald', null),
        (6, 'Ancient Nucleus', null),
        (7, 'Ancient Orb', null),
        (8, 'Angelfish', null),
        (9, 'Animal Claws', null),
        (10, 'Animal Droppings', null),
        (11, 'Animal Fang', null),
        (12, 'Animal Hide', null),
        (13, 'Antenna Lantern', null),
        (14, 'Antidote Berries', null),
        (15, 'Antipara Berries', null),
        (16, 'Blue Paint', 1),
        (17, 'Red Paint', 2),
        (18, 'Yellow Paint', 3),
        (19, 'White Paint', 4),
        (20, 'Black Paint', 5),
        (21, 'Rainbow Paint', 6),
        (22, 'Spooky Lamp', 34),
        (23, 'Hay', 46),
        (24, 'Encyclopedia', 157),
        (25, 'Boiled Egg', 185),
        (26, 'Apple Juice', 247),
        (27, 'Royal Flan', 267),
        (28, 'Vegetable Stew', 272),
        (29, 'Wheat Juice', 273),
        (30, 'Golden Apple Pie', 274),
        (31, 'Creamy Curry', 275),
        (32, 'Salud Glass', 306),
        (34, 'Aquamarine', null),
        (35, 'Arch Alcheweed', null),
        (36, 'Armored Onion', null),
        (37, 'Aubergine', null),
        (38, 'Bass of Darkness', null),
        (39, 'Beach Watermelon', null),
        (40, 'Beast Hide', null),
        (41, 'Beef', null),
        (42, 'Beelzebub Tuna', null),
        (43, 'Big Egg', null),
        (44, 'Big Tail', null),
        (45, 'Bigbeak Egg', null),
        (46, 'Black Anthurium', null),
        (47, 'Black Onyx', null),
        (48, 'Black Pepper', null),
        (49, 'Black Sheep Fleece', null),
        (50, 'Blackgill', null),
        (51, 'Blue Anthurium', null),
        (52, 'Blue Gel', null),
        (53, 'Blue Stone', null),
        (54, 'Bluescale Lordfish', null),
        (55, 'Brilliant Feather', null),
        (56, 'Broccoli', null),
        (57, 'Bushy Baatato', null),
        (58, 'Butter', null),
        (59, 'Cabbage', null),
        (60, 'Cactus Fish', null),
        (61, 'Calmaryllis', null),
        (62, 'Carrot', null),
        (63, 'Castele Apple', null),
        (64, 'Cave Catfish', null),
        (65, 'Cave Strawberries', null),
        (66, 'Charoite', null),
        (67, 'Cherry', null),
        (68, 'Cherry Branch', null),
        (69, 'Cherry Honey', null),
        (70, 'Cherry Log', null),
        (71, 'Cherry Lordfish', null),
        (72, 'Cherry Lordfish Moss', null),
        (73, 'Cherry Nectar', null),
        (74, 'Chicken', null),
        (75, 'Chicken Eggs', null),
        (76, 'Clownfish', null),
        (77, 'Coal-Black Feather', null),
        (78, 'Coconut', null),
        (79, 'Coldwater Tuna', null),
        (80, 'Combustible Powder', null),
        (81, 'Corrupt Carrot', null),
        (82, 'Crimson Carrot', null),
        (83, 'Crystalized Scale', null),
        (84, 'Crystalline Bass', null),
        (85, 'Cureweed', null),
        (86, 'Curious Object', null),
        (87, 'Curry Spices', null),
        (88, 'Cute Ribbon', null),
        (89, 'Dandelion Puff', null),
        (90, 'Dandy Potato', null),
        (91, 'Dark Gem', null),
        (92, 'Dark Honey', null),
        (93, 'Dark Monster Core', null),
        (94, 'Dark Scales', null),
        (95, 'Dark Stone', null),
        (96, 'Darkfish', null),
        (97, 'Darktree Bark', null),
        (98, 'Darktree Sap', null),
        (99, 'Darkwood Log', null),
        (100, 'Deadly Claws', null),
        (101, 'Deep Sea Lordfish', null),
        (102, 'Demonic Powder', null),
        (103, 'Demonion', null),
        (104, 'Desert Log', null),
        (105, 'Devil''s Fin', null),
        (106, 'Diamond', null),
        (107, 'Dino Meat', null),
        (108, 'Divine Ribbon', null),
        (109, 'Dragon Leg Bone', null),
        (110, 'Dragon Meat', null),
        (111, 'Dragon Skull', null),
        (112, 'Dragon Vertebrae', null),
        (113, 'Dragontree Horn', null),
        (114, 'Dragontree Wing', null),
        (115, 'Duffle', null),
        (116, 'Dunefin Tuna', null),
        (117, 'Durable Shell', null),
        (118, 'Earth Log', null),
        (119, 'Earth Mana', null),
        (120, 'Earth Shard', null),
        (121, 'Elder Cherry Log', null),
        (122, 'Elder Darkwood Log', null),
        (123, 'Elder Desert Log', null),
        (124, 'Elder Earth Log', null),
        (125, 'Elder Fire Log', null),
        (126, 'Elder Oak Log', null),
        (127, 'Elder Palm Log', null),
        (128, 'Elder Pine Log', null),
        (129, 'Elder Skytree Log', null),
        (130, 'Elder Starry Log', null),
        (131, 'Elder Sugar Log', null),
        (132, 'Elder Water Log', null),
        (133, 'Elder Wind Log', null),
        (134, 'Electric Eel', null),
        (135, 'Emerald', null),
        (136, 'Eruptuna', null),
        (137, 'Evening Glory', null),
        (138, 'Evil Carp', null),
        (139, 'Evil Shard', null),
        (140, 'Extra Creamy Milk', null),
        (141, 'Faintly Glowing Leaf', null),
        (142, 'Fallen Carrot', null),
        (143, 'Faraway Iron', null),
        (144, 'Faraway Rice', null),
        (145, 'Faraway Spring Water', null),
        (146, 'Faraway Sweetfish', null),
        (147, 'Faraway Wheat', null),
        (148, 'Fire Log', null),
        (149, 'Fire Mana', null),
        (150, 'Fire Shard', null),
        (151, 'Fish Scales', null),
        (152, 'Flame Ruby', null),
        (153, 'Flaming Mohawk', null),
        (154, 'Flax Thread', null),
        (155, 'Flaxen Hair', null),
        (156, 'Fluffy Ribbon', null),
        (157, 'Flying Fish', null),
        (158, 'Forest Lordfish', null),
        (159, 'Forest Lordfish Moss', null),
        (160, 'Fortune''s Fluff', null),
        (161, 'Fossil Shard', null),
        (162, 'Fossilshroom', null),
        (163, 'Frost Crystal', null),
        (164, 'Gemini Cabbage', null),
        (165, 'Ghastly Powder', null),
        (166, 'Ghost Meat', null),
        (167, 'Giant Claws', null),
        (168, 'Giant Fang', null),
        (169, 'Giant Horn', null),
        (170, 'Giant Mandrake', null),
        (171, 'Giant Scale', null),
        (172, 'Giant Tail', null),
        (173, 'Giant Thorn', null),
        (174, 'Giant''s Tree Bark', null),
        (175, 'Giant''s Tree Nuts', null),
        (176, 'Gigaga Truffle', null),
        (177, 'Ginger', null),
        (178, 'Glittering Coral', null),
        (179, 'Glossy Feather', null),
        (180, 'Goat Fleece', null),
        (181, 'Godfish', null),
        (182, 'Godfish Moss', null),
        (183, 'Godly Cabbage', null),
        (184, 'Gold Koi', null),
        (185, 'Golden Apple', null),
        (186, 'Golden Droppings', null),
        (187, 'Golden Fin', null),
        (188, 'Golden Goat Fleece', null),
        (189, 'Golden String', null),
        (190, 'Golden Swordfish', null),
        (191, 'Goldweed', null),
        (192, 'Golem Fragment', null),
        (193, 'Good Mysteria Masonry', null),
        (194, 'Gourdy Pumpkin', null),
        (195, 'Great Lucky Bream', null),
        (196, 'Great Prairie''s Tear', null),
        (197, 'Great Spirit Flower', null),
        (198, 'Great Spirit Radish', null),
        (199, 'Green Fish', null),
        (200, 'Green Gel', null),
        (201, 'Haniwa Jewel', null),
        (202, 'Haniwa Stone', null),
        (203, 'Hard Claws', null),
        (204, 'Healweed', null),
        (205, 'Hermit Carrot', null),
        (206, 'High-Flying Fish', null),
        (207, 'Hot Spring Bream', null),
        (208, 'Icy Claws', null),
        (209, 'Icy Scales', null),
        (210, 'Impeccable Stache', null),
        (211, 'Invincible Onionskin', null),
        (212, 'Island Banana', null),
        (213, 'Island Pear', null),
        (214, 'Kaiser Pumpkin', null),
        (215, 'Kissyfish', null),
        (216, 'Lavashrimp', null),
        (217, 'Leather String', null),
        (218, 'Legendary Divine Log', null),
        (219, 'Legendary Don Horn', null),
        (220, 'Legendary Don Meat', null),
        (221, 'Legendary King Spud', null),
        (222, 'Legendary Rocket Fish', null),
        (223, 'Legendary Shiny Diamond', null),
        (224, 'Lifeforce Cluster', null),
        (225, 'Lifeweed', null),
        (226, 'Light Mana', null),
        (227, 'Little Shell', null),
        (228, 'Little Tail', null),
        (229, 'Lucky Pearl', null),
        (230, 'Lulab Trout', null),
        (231, 'Magic Ore', null),
        (232, 'Magic Powder', null),
        (233, 'Magma Dragonstone', null),
        (234, 'Magma Fin', null),
        (235, 'Magma Ore', null),
        (236, 'Marine Ore', null),
        (237, 'Marine Thread', null),
        (238, 'Metal Buttons', null),
        (239, 'Milk', null),
        (240, 'Minty Ore', null),
        (241, 'Monster Crystal', null),
        (242, 'Monster Hide', null),
        (243, 'Monster Meat', null),
        (244, 'Monster Tail', null),
        (245, 'Moon Cluster', null),
        (246, 'Mungus Radish', null),
        (247, 'Mushroom', null),
        (248, 'Mustard', null),
        (249, 'Mutton', null),
        (250, 'Mysteria Carp', null),
        (251, 'Mysteria Copper', null),
        (252, 'Mysteria Crucian', null),
        (253, 'Mysteria Koi', null),
        (254, 'Mysteria Masonry', null),
        (255, 'Mysteria Mineral Water', null),
        (256, 'Mysterious Object', null),
        (257, 'Mystfruit', null),
        (258, 'Mythical Meat', null),
        (259, 'Napdragon''s Scale', null),
        (260, 'Napdragon''s Teardrop', null),
        (261, 'Nearly Invisible Teardrop', null),
        (262, 'Nimbus Scales', null),
        (263, 'Noble Goat Fleece', null),
        (264, 'Oak Log', null),
        (265, 'Onion', null),
        (266, 'Pale Onion', null),
        (267, 'Palm Log', null),
        (268, 'Palm Nuts', null),
        (269, 'Paralysis Powder', null),
        (270, 'Parasol Fish', null),
        (271, 'Pine Log', null),
        (272, 'Pine Nuts', null),
        (273, 'Pink Silk Thread', null),
        (274, 'Pirate Captain Buttons', null),
        (275, 'Plains Lordfish', null),
        (276, 'Plains Lordfish Moss', null),
        (277, 'Platinum Ore', null),
        (278, 'Poison Powder', null),
        (279, 'Poseidon Swordfish', null),
        (280, 'Poseidon''s Fin', null),
        (281, 'Potato', null),
        (282, 'Prairie Grapes', null),
        (283, 'Prairie Honey', null),
        (284, 'Pretty Coral', null),
        (285, 'Pufferfish', null),
        (286, 'Pumpkin', null),
        (287, 'Puriffodil', null),
        (288, 'Purple Cabbage', null),
        (289, 'Purple Stone', null),
        (290, 'Python Scales', null),
        (291, 'Quality Minty Ore', null),
        (292, 'Quartzfish', null),
        (293, 'Queen Eggs', null),
        (294, 'Quetzal Egg', null),
        (295, 'Quetzal Treasure', null),
        (296, 'Radish', null),
        (297, 'Radishy Leaf', null),
        (298, 'Raging Radish', null),
        (299, 'Rainbow Feather', null),
        (300, 'Rainbow Fin', null),
        (301, 'Rainbow Flying Fish', null),
        (302, 'Red Anthurium', null),
        (303, 'Red Gel', null),
        (304, 'Red Peppercorn', null),
        (305, 'Red Serpent Scales', null),
        (306, 'Redgill', null),
        (307, 'Rejuvenating Berries', null),
        (308, 'Remote Island Honey', null),
        (309, 'Royal Eggs', null),
        (310, 'Ruby', null),
        (311, 'Rushdelion', null),
        (312, 'Sack of Gold', null),
        (313, 'Sack of Silver', null),
        (314, 'Sack of Treasure', null),
        (315, 'Salt', null),
        (316, 'Sand Fish', null),
        (317, 'Sandstone', null),
        (318, 'Sapphire', null),
        (319, 'Sardine', null),
        (320, 'Seashell Buttons', null),
        (321, 'Shadow Carrot', null),
        (322, 'Shadow Mana', null),
        (323, 'Shadow-Soaked Hide', null),
        (324, 'Sharp Claws', null),
        (325, 'Sheep Fleece', null),
        (326, 'Sheep King''s Fleece', null),
        (327, 'Silk Thread', null),
        (328, 'Skeletal Horn', null),
        (329, 'Skeleton Fish', null),
        (330, 'Skytree Log', null),
        (331, 'Smelt', null),
        (332, 'Smiley Pumpkin', null),
        (333, 'Smoldering Claws', null),
        (334, 'Smoldering Fang', null),
        (335, 'Smoldering Hide', null),
        (336, 'Snake Scales', null),
        (337, 'Sneakfish', null),
        (338, 'Sneaky Tuna', null),
        (339, 'Soulweed', null),
        (340, 'Spiritual Powder', null),
        (341, 'Spooky Spud', null),
        (342, 'Star Apple', null),
        (343, 'Star Cluster', null),
        (344, 'Starry Log', null),
        (345, 'Starry Thread', null),
        (346, 'Steel Shell', null),
        (347, 'Straw Thread', null),
        (348, 'String', null),
        (349, 'Strong Fang', null),
        (350, 'Stunning Coral', null),
        (351, 'Sturdy Fang', null),
        (352, 'Subterranean Scales', null),
        (353, 'Sugar', null),
        (354, 'Sugar Log', null),
        (355, 'Sugar Nuts', null),
        (356, 'Sultan Heart', null),
        (357, 'Sultan Stone', null),
        (358, 'Sun Cluster', null),
        (359, 'Sunny Puff', null),
        (360, 'Suspicious Object', null),
        (361, 'Sweetcorn', null),
        (362, 'Swolean Gold', null),
        (363, 'Swordfish', null),
        (364, 'Swordfish Fin', null),
        (365, 'Thick Fang', null),
        (366, 'Thick Shell', null),
        (367, 'Tomato', null),
        (368, 'Top-Class Mushroom', null),
        (369, 'Topaz', null),
        (370, 'Trial Cavedew', null),
        (371, 'Tropica Bream', null),
        (372, 'Tropica Deep Sea Water', null),
        (373, 'Tropica Silver', null),
        (374, 'Truffle', null),
        (375, 'Tuna', null),
        (376, 'Tunoco Fish', null),
        (377, 'Turtle Shell', null),
        (378, 'Uber-Rich Milk', null),
        (379, 'Ultima Alcheweed', null),
        (380, 'Valuable Shell', null),
        (381, 'Vinegar', null),
        (382, 'Vitabloom', null),
        (383, 'Vitalweed', null),
        (384, 'Wakeup Berries', null),
        (385, 'Water Log', null),
        (386, 'Water Mana', null),
        (387, 'Water Shard', null),
        (388, 'Weird Object', null),
        (389, 'White Anthurium', null),
        (390, 'White Butterfly', null),
        (391, 'Wicked Mandrake', null),
        (392, 'Wild Antler', null),
        (393, 'Wild Beast Meat', null),
        (394, 'Wild Bull Horn', null),
        (395, 'Wild Kiwi', null),
        (396, 'Wind Log', null),
        (397, 'Wind Mana', null),
        (398, 'Wind Shard', null),
        (399, 'Wonderful Ribbon', null),
        (400, 'Wooden Buttons', null),
        (401, 'Yellow Anthurium', null),
        (402, 'Yellow Gel', null),
        (403, 'Yellow Stone', null),
        (419, 'Axe of Time', 503),
        (420, 'Bow of Time', 394),
        (421, 'Brush of Time', 590),
        (422, 'Cherry Axe', 482),
        (423, 'Cherry Lumber', 334),
        (424, 'Crate', 638),
        (425, 'Darkwood Lumber', 342),
        (426, 'Desert Lumber', 332),
        (427, 'Earth Wood Lumber', 340),
        (428, 'Fire Wood Lumber', 337),
        (429, 'Oak Axe', 476),
        (430, 'Oak Bow', 346),
        (431, 'Oak Lumber', 330),
        (432, 'Oak Rod', 505),
        (433, 'Oak Saw', 534),
        (434, 'Palm Lumber', 331),
        (435, 'Pine Lumber', 333),
        (436, 'Pine Saw', 537),
        (437, 'Rod of Time', 532),
        (438, 'Saw of Time', 561),
        (439, 'Skytree Lumber', 336),
        (440, 'Staff of Time', 447),
        (441, 'Starry Lumber', 341),
        (442, 'Sugar Lumber', 335),
        (443, 'Water Wood Lumber', 338),
        (444, 'Wind Wood Lumber', 339),
        (445, 'Black Wool', 761),
        (446, 'Cashmere', 763),
        (447, 'Dandelion Cotton', 759),
        (448, 'Flare Cashmere', 765),
        (449, 'Linen', 764),
        (450, 'Marine Silk', 768),
        (451, 'Pink Silk', 769),
        (452, 'Silk', 762),
        (453, 'Stardust Linen', 767),
        (454, 'Sunny Cotton', 766),
        (455, 'Wool', 760),
        (456, 'Woven Straw Fabric', 758),
        (457, 'King''s Wool', 770),
        (458, 'Yarn Ball', 769),
        (459, 'Blank Canvas', 700),
        (460, 'Hand Woven Basket', 754),
        (461, 'Bronze Ingot', 1711),
        (462, 'Iron Ingot', 1712),
        (463, 'Silver Ingot', 1713),
        (464, 'Marine Ingot', 1714),
        (465, 'Platinum Ingot', 1715),
        (466, 'Gold Ingot', 1716),
        (467, 'Magma Ingot', 1717),
        (468, 'Magic Ingot', 1718),
        (469, 'Flame Saber', 1731),
        (470, 'Sword of Time', 1776),
        (471, 'Iron Shield', 1784),
        (472, 'Silver Shield', 1787),
        (473, 'Shield of Time', 1820),
        (474, 'Greatsword of Time', 1873),
        (475, 'Iron Pickaxe', 1878),
        (476, 'Pickaxe of Time', 1902),
        (477, 'Iron Hoe', 1907),
        (478, 'Hoe of Time', 1931),
        (479, 'Frying Pan of Time', 1960),
        (480, 'Bronze Hammer', 1962),
        (481, 'Hammer of Time', 1989),
        (482, 'Bronze Needle', 1991),
        (483, 'Needle of Time', 2018),
        (484, 'Campfire', 2195),
        (485, 'Tea Set', 2197),
        (486, 'Healing Powder', 2381),
        (487, 'Elixir', 2354),
        (488, 'Sealing Potion', 2430),
        (489, 'Poison Antidote', 2410),
        (490, 'Power Aid', 2412),
        (491, 'Magic Aid', 2393),
        (492, 'Wooden Palette', 100),
        (493, 'Frozen Remedy', 2365),
        (494, 'Flask Of Time', 2362),
        (495, 'Burning Remedy', 2338),
        (496, 'Paralysis Antidote', 2406),
        (497, 'Energy Powder', 2356),
        (498, 'Candle', 2339),
        (499, 'Resistance Aid', 2418),
        (500, 'Science Flask', 2426),
        (501, 'Hi-Hp Potion', 2383);