insert into material_sources (material_id, collection_type, profession_name, map_name, target_name, id)
values  (47, 'Gathering', 'Miner', 'Treasure Grove', 'Magic Ore Deposit', 1),
        (47, 'Gathering', 'Miner', 'Treasure Grove', 'Luminous Magic Ore Deposit', 2),
        (47, 'Gathering', 'Miner', 'Depths - B3', 'Graphite Deposit', 3),
        (48, 'Restaurant', 'N/A', 'Eternia Village', 'None', 4),
        (48, 'Restaurant', 'N/A', 'Capital of Mysteria', 'None', 5),
        (48, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 6),
        (48, 'Tool Shop', 'N/A', 'Ginomorsia', 'None', 7),
        (49, 'Material Shop', 'N/A', 'Capital of Mysteria', 'None', 8),
        (49, 'Combat', 'N/A', 'Capital of Mysteria', 'Black Woolie', 9),
        (49, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 10),
        (49, 'Tool Shop', 'N/A', 'Ginomorsia', 'None', 11),
        (50, 'Restaurant', 'N/A', 'Swolean Island', 'None', 12),
        (50, 'Gathering', 'Angler', 'Depths - B2', 'Small Fish Shadow', 13),
        (51, 'Material Shop', 'N/A', 'Capital of Mysteria', 'None', 14),
        (51, 'Material Shop', 'N/A', 'Capital of Mysteria', 'None', 15),
        (51, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 16),
        (51, 'Tool Shop', 'N/A', 'Ginomorsia', 'None', 17),
        (52, 'Material Shop', 'N/A', 'Tropica Isles', 'None', 18),
        (52, 'Combat', 'N/A', 'Depths - B2', 'Splash Frog', 19),
        (53, 'Material Shop', 'N/A', 'Faraway Island', 'None', 20),
        (53, 'Gathering', 'Miner', 'Depths - B1', 'Superior Blue Ore Deposit', 21),
        (53, 'Combat', 'N/A', 'Treasure Grove', 'Gemeleon', 22),
        (53, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 23),
        (54, 'Gathering', 'Angler', 'Cave of Trials B3', 'Bluescale Lordfish', 24),
        (55, 'Combat', 'N/A', 'Capital of Mysteria', 'Tunoco Quetzal', 25),
        (56, 'Restaurant', 'N/A', 'Faraway Island', 'None', 26),
        (56, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 27),
        (56, 'Tool Shop', 'N/A', 'Ginomorsia', 'None', 28),
        (57, 'Material Shop', 'N/A', 'Lulab Forest', 'None', 29),
        (57, 'Crafting', 'Farmer', 'Base Camp', 'Potato', 30),
        (57, 'Crafting', 'Farmer', 'Base Camp', 'Spooky Spud', 31),
        (58, 'Restaurant', 'N/A', 'Faraway Island', 'None', 32),
        (58, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 33),
        (58, 'Tool Shop', 'N/A', 'Ginomorsia', 'None', 34),
        (59, 'Crafting', 'Farmer', 'Base Camp', 'Cabbage', 35),
        (59, 'Crafting', 'Farmer', 'Base Camp', 'Godly Cabbage', 36),
        (59, 'Material Shop', 'N/A', 'Faraway Island', 'None', 37),
        (59, 'Restaurant', 'N/A', 'Faraway Island', 'None', 38),
        (60, 'Restaurant', 'N/A', 'Swolean Island', 'None', 39),
        (60, 'Gathering', 'Angler', 'Depths - B2', 'Small Fish Shadow', 40),
        (61, 'Material Shop', 'N/A', 'Tropica Isles', 'None', 41),
        (61, 'Material Shop', 'N/A', 'Depths - B3', 'None', 42),
        (61, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 43),
        (61, 'Material Shop', 'N/A', 'Treasure Grove', 'None', 44),
        (62, 'Crafting', 'Farmer', 'Base Camp', 'Carrot', 45),
        (62, 'Material Shop', 'N/A', 'Faraway Island', 'None', 46),
        (62, 'Restaurant', 'N/A', 'Faraway Island', 'None', 47),
        (62, 'Combat', 'N/A', 'Faraway Island', 'Carroty', 48),
        (63, 'Restaurant', 'N/A', 'Capital of Mysteria', 'None', 49),
        (63, 'Material Shop', 'N/A', 'Lulab Forest', 'None', 50),
        (63, 'Material Shop', 'N/A', 'Treasure Grove', 'None', 51),
        (63, 'Combat', 'N/A', 'Faraway Island', 'Applejack Ape', 52),
        (64, 'Restaurant', 'N/A', 'Swolean Island', 'None', 53),
        (64, 'Gathering', 'Angler', 'Depths - B2', 'Big Fish Shadow', 54),
        (65, 'Restaurant', 'N/A', 'Swolean Island', 'None', 55),
        (65, 'Combat', 'N/A', 'Ginomorsia', 'Burly Gorilla', 56),
        (65, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 57),
        (65, 'Tool Shop', 'N/A', 'Ginomorsia', 'None', 58),
        (66, 'Gathering', 'Miner', 'Treasure Grove', 'Luminous Magic Ore Deposit', 59),
        (67, 'Restaurant', 'N/A', 'Tropica Isles', 'None', 60),
        (67, 'Material Shop', 'N/A', 'Treasure Grove', 'None', 61),
        (67, 'Combat', 'N/A', 'Lulab Forest', 'Pseudo Cherry', 62),
        (67, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 63),
        (68, 'Woodcutting', 'Woodcutter', 'Lulab Forest', 'Recluse Cherry Tree', 64),
        (69, 'Restaurant', 'N/A', 'Faraway Island', 'None', 65),
        (69, 'Combat', 'N/A', 'Faraway Island', 'Peach Bee', 66),
        (69, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 67),
        (70, 'Material Shop', 'N/A', 'Faraway Island', 'None', 68),
        (70, 'Woodcutting', 'Woodcutter', 'Faraway Island', 'Cherry Tree', 69),
        (70, 'Combat', 'N/A', 'Lulab Forest', 'Pseudo Cherry', 70),
        (70, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 71),
        (137, 'Material Shop', 'N/A', 'Capital of Mysteria', 'None', 72),
        (71, 'Gathering', 'Angler', 'Lulab Forest', 'Cherry Lordfish', 73),
        (71, 'Material Shop', 'N/A', 'Tropica Isles', 'None', 74),
        (72, 'Gathering', 'Angler', 'Lulab Forest', 'Cherry Lordfish', 75),
        (137, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 76),
        (72, 'Material Shop', 'N/A', 'Tropica Isles', 'None', 77),
        (73, 'Woodcutting', 'Woodcutter', 'Lulab Forest', 'Recluse Cherry Tree', 78),
        (74, 'Restaurant', 'N/A', 'Eternia Village', 'None', 79),
        (74, 'Combat', 'N/A', 'Faraway Island', 'Razorbeak', 80),
        (74, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 81),
        (74, 'Tool Shop', 'N/A', 'Ginomorsia', 'None', 82),
        (137, 'Material Shop', 'N/A', 'Treasure Grove', 'None', 83),
        (75, 'Restaurant', 'N/A', 'Eternia Village', 'None', 84),
        (138, 'Gathering', 'Angler', 'Treasure Grove', 'Small Fish Shadow', 85),
        (75, 'Material Shop', 'N/A', 'Eternia Village', 'None', 86),
        (75, 'Combat', 'N/A', 'Faraway Island', 'Razorbeak', 87),
        (139, 'Combat', 'N/A', 'Treasure Grove', 'Lord of Death', 88),
        (75, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 89),
        (140, 'Restaurant', 'N/A', 'Faraway Island', 'None', 90),
        (76, 'Restaurant', 'N/A', 'Tropica Isles', 'None', 91),
        (140, 'Restaurant', 'N/A', 'Swolean Island', 'None', 92),
        (76, 'Gathering', 'Angler', 'Base Camp', 'Small Fish Shadow', 93),
        (140, 'Combat', 'N/A', 'Cave of Trials B4', 'Taurus', 94),
        (77, 'Material Shop', 'N/A', 'Tropica Isles', 'None', 95),
        (77, 'Combat', 'N/A', 'Da Finci Cave', 'Umbral Runner', 96),
        (78, 'Restaurant', 'N/A', 'Tropica Isles', 'None', 97),
        (78, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 98),
        (78, 'Tool Shop', 'N/A', 'Ginomorsia', 'None', 99),
        (79, 'Gathering', 'Angler', 'Depths - B2', 'Coldwater Tuna', 100),
        (80, 'Material Shop', 'N/A', 'Capital of Mysteria', 'None', 101),
        (80, 'Combat', 'N/A', 'Capital of Mysteria', 'Cornella', 102),
        (80, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 103),
        (80, 'Tool Shop', 'N/A', 'Ginomorsia', 'None', 104),
        (81, 'Crafting', 'Farmer', 'Base Camp', 'Shadow Carrot', 105),
        (81, 'Crafting', 'Farmer', 'Base Camp', 'Wicked Mandrake', 106),
        (82, 'Crafting', 'Farmer', 'Base Camp', 'Carrot', 107),
        (82, 'Crafting', 'Farmer', 'Base Camp', 'Giant Mandrake', 108),
        (82, 'Material Shop', 'N/A', 'Lulab Forest', 'None', 109),
        (82, 'Combat', 'N/A', 'Faraway Island', 'Carrotella', 110),
        (83, 'Gathering', 'Angler', 'Depths - B3', 'Crystalline Bass', 111),
        (84, 'Gathering', 'Angler', 'Depths - B3', 'Crystalline Bass', 112),
        (85, 'Material Shop', 'N/A', 'Eternia Village', 'None', 113),
        (85, 'Material Shop', 'N/A', 'Eternia Village', 'None', 114),
        (85, 'Combat', 'N/A', 'Ginomorsia', 'Crimson Weedling', 115),
        (85, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 116),
        (86, 'Material Shop', 'N/A', 'Faraway Island', 'None', 117),
        (86, 'Combat', 'N/A', 'Lulab Forest', 'Fluff Baller', 118),
        (86, 'Combat', 'N/A', 'Depths - B2', 'Greater Sea Beetle Baller', 119),
        (86, 'Combat', 'N/A', 'Depths - B2', 'Snow Beetle Baller', 120),
        (87, 'Restaurant', 'N/A', 'Swolean Island', 'None', 121),
        (87, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 122),
        (87, 'Tool Shop', 'N/A', 'Ginomorsia', 'None', 123),
        (88, 'Material Shop', 'N/A', 'Capital of Mysteria', 'None', 124),
        (88, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 125),
        (89, 'Material Shop', 'N/A', 'Eternia Village', 'None', 126),
        (89, 'Material Shop', 'N/A', 'Eternia Village', 'None', 127),
        (89, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 128),
        (89, 'Tool Shop', 'N/A', 'Ginomorsia', 'None', 129),
        (90, 'Crafting', 'Farmer', 'Base Camp', 'Potato', 130),
        (90, 'Crafting', 'Farmer', 'Base Camp', 'Spooky Spud', 131),
        (91, 'Gathering', 'Miner', 'Treasure Grove', 'Luminous Magic Ore Deposit', 132),
        (92, 'Restaurant', 'N/A', 'Tropica Isles', 'None', 133),
        (92, 'Combat', 'N/A', 'Treasure Grove', 'Killer Hornet', 134),
        (93, 'Combat', 'N/A', 'Treasure Grove', 'Shadow Carroty', 135),
        (93, 'Combat', 'N/A', 'Treasure Grove', 'Shadow Carrotella', 136),
        (93, 'Combat', 'N/A', 'Treasure Grove', 'Shadow Behemoth', 137),
        (94, 'Gathering', 'Angler', 'Tropica Isles', 'Bass of Darkness', 138),
        (94, 'Material Shop', 'N/A', 'Tropica Isles', 'None', 139),
        (95, 'Gathering', 'Miner', 'Depths - B3', 'Graphite Deposit', 140),
        (140, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 141),
        (96, 'Gathering', 'Angler', 'Treasure Grove', 'Rare Fish Shadow', 142),
        (97, 'Woodcutting', 'Woodcutter', 'Treasure Grove', 'Luminous Darkwood Tree', 143),
        (98, 'Woodcutting', 'Woodcutter', 'Treasure Grove', 'Luminous Darkwood Tree', 144),
        (99, 'Woodcutting', 'Woodcutter', 'Depths - B3', 'Darkwood Tree', 145),
        (99, 'Woodcutting', 'Woodcutter', 'Depths - B3', 'Great Darkwood Tree', 146),
        (99, 'Woodcutting', 'Woodcutter', 'Treasure Grove', 'Luminous Darkwood Tree', 147),
        (100, 'Material Shop', 'N/A', 'Swolean Island', 'None', 148),
        (100, 'Combat', 'N/A', 'Depths - B2', 'Cave Panther', 149),
        (100, 'Combat', 'N/A', 'Treasure Grove', 'Licky Gecko', 150),
        (101, 'Gathering', 'Angler', 'Depths - B3', 'Deep Sea Lordfish', 151),
        (102, 'Combat', 'N/A', 'Depths - B2', 'Wicked Spooky', 152),
        (102, 'Combat', 'N/A', 'Treasure Grove', 'Shadow Spooky', 153),
        (103, 'Crafting', 'Farmer', 'Base Camp', 'Onion', 154),
        (104, 'Woodcutting', 'Woodcutter', 'Ginomorsia', 'Desert Tree', 155),
        (104, 'Woodcutting', 'Woodcutter', 'Ginomorsia', 'Great Desert Tree', 156),
        (104, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 157),
        (104, 'Tool Shop', 'N/A', 'Ginomorsia', 'None', 158),
        (105, 'Gathering', 'Angler', 'Treasure Grove', 'Beelzebub Tuna', 159),
        (106, 'Gathering', 'Miner', 'Cave of Trials B2', 'Earth Starcrystal', 160),
        (107, 'Combat', 'N/A', 'Depths - B3', 'Mohawkasaurus', 161),
        (107, 'Combat', 'N/A', 'Treasure Grove', 'Lord of Death', 162),
        (141, 'Crafting', 'Farmer', 'Base Camp', 'Godly Cabbage', 163),
        (142, 'Crafting', 'Farmer', 'Base Camp', 'Shadow Carrot', 164),
        (142, 'Crafting', 'Farmer', 'Base Camp', 'Wicked Mandrake', 165),
        (108, 'Material Shop', 'N/A', 'Swolean Island', 'None', 166),
        (108, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 167),
        (109, 'Gathering', 'Miner', 'Depths - B2', 'Ancient Fossil', 168),
        (109, 'Gathering', 'Miner', 'Depths - B3', 'Giant Ancient Fossil', 169),
        (110, 'Combat', 'N/A', 'Lulab Forest', 'Prairie Dragon', 170),
        (110, 'Combat', 'N/A', 'Cave of Trials B4', 'Napdragon', 171),
        (111, 'Gathering', 'Miner', 'Depths - B2', 'Ancient Fossil', 172),
        (111, 'Gathering', 'Miner', 'Depths - B3', 'Giant Ancient Fossil', 173),
        (112, 'Gathering', 'Miner', 'Depths - B2', 'Ancient Fossil', 174),
        (112, 'Gathering', 'Miner', 'Depths - B3', 'Giant Ancient Fossil', 175),
        (113, 'Woodcutting', 'Woodcutter', 'Treasure Grove', 'Great Dragontree', 176),
        (114, 'Woodcutting', 'Woodcutter', 'Treasure Grove', 'Great Dragontree', 177),
        (115, 'Material Shop', 'N/A', 'Lulab Forest', 'None', 178),
        (115, 'Material Shop', 'N/A', 'Lulab Forest', 'None', 179),
        (115, 'Material Shop', 'N/A', 'Treasure Grove', 'None', 180),
        (116, 'Gathering', 'Angler', 'Base Camp', 'Big Fish Shadow', 181),
        (117, 'Material Shop', 'N/A', 'Tropica Isles', 'None', 182),
        (117, 'Material Shop', 'N/A', 'Tropica Isles', 'None', 183),
        (117, 'Combat', 'N/A', 'Tropica Isles', 'Stelleroid', 184),
        (117, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 185),
        (118, 'Woodcutting', 'Woodcutter', 'Swolean Island', 'Earth Angeltree', 186),
        (119, 'Woodcutting', 'Woodcutter', 'Swolean Island', 'Earth Angeltree', 187),
        (119, 'Gathering', 'Miner', 'Cave of Trials B2', 'Earth Starcrystal', 188),
        (119, 'Combat', 'N/A', 'Lulab Forest', 'Prairie Dragon', 189),
        (119, 'Combat', 'N/A', 'Tropica Isles', 'Steel Tortortoise', 190),
        (120, 'Gathering', 'Miner', 'Cave of Trials B2', 'Earth Starcrystal', 191),
        (121, 'Woodcutting', 'Woodcutter', 'Faraway Island', 'Cherry Tree', 192),
        (121, 'Woodcutting', 'Woodcutter', 'Lulab Forest', 'Great Cherry Tree', 193),
        (121, 'Combat', 'N/A', 'Lulab Forest', 'Pseudo Cherry', 194),
        (122, 'Woodcutting', 'Woodcutter', 'Depths - B3', 'Darkwood Tree', 195),
        (122, 'Woodcutting', 'Woodcutter', 'Depths - B3', 'Great Darkwood Tree', 196),
        (122, 'Woodcutting', 'Woodcutter', 'Treasure Grove', 'Luminous Darkwood Tree', 197),
        (123, 'Woodcutting', 'Woodcutter', 'Ginomorsia', 'Desert Tree', 198),
        (123, 'Woodcutting', 'Woodcutter', 'Ginomorsia', 'Great Desert Tree', 199),
        (124, 'Woodcutting', 'Woodcutter', 'Swolean Island', 'Earth Angeltree', 200),
        (125, 'Woodcutting', 'Woodcutter', 'Capital of Mysteria', 'Fire Angeltree', 201),
        (126, 'Material Shop', 'N/A', 'Tropica Isles', 'None', 202),
        (126, 'Woodcutting', 'Woodcutter', 'Eternia Village', 'Oak Tree', 203),
        (126, 'Woodcutting', 'Woodcutter', 'Capital of Mysteria', 'Great Oak Tree', 204),
        (126, 'Combat', 'N/A', 'Lulab Forest', 'Pseudo Oak', 205),
        (127, 'Material Shop', 'N/A', 'Tropica Isles', 'None', 206),
        (127, 'Woodcutting', 'Woodcutter', 'Eternia Village', 'Palm Fruit Tree', 207),
        (127, 'Woodcutting', 'Woodcutter', 'Eternia Village', 'Palm Tree', 208),
        (127, 'Woodcutting', 'Woodcutter', 'Capital of Mysteria', 'Great Palm Tree', 209),
        (128, 'Woodcutting', 'Woodcutter', 'Faraway Island', 'Pine Tree', 210),
        (128, 'Woodcutting', 'Woodcutter', 'Lulab Forest', 'Great Pine Tree', 211),
        (129, 'Woodcutting', 'Woodcutter', 'Cave of Trials', 'Skytree', 212),
        (129, 'Woodcutting', 'Woodcutter', 'Cave of Trials', 'Great Skytree', 213),
        (130, 'Woodcutting', 'Woodcutter', 'Depths - B2', 'Starry Tree', 214),
        (130, 'Woodcutting', 'Woodcutter', 'Depths - B2', 'Great Starry Tree', 215),
        (131, 'Material Shop', 'N/A', 'Tropica Isles', 'None', 216),
        (131, 'Woodcutting', 'Woodcutter', 'Tropica Isles', 'Sugar Tree', 217),
        (131, 'Woodcutting', 'Woodcutter', 'Tropica Isles', 'Great Sugar Tree', 218),
        (143, 'Material Shop', 'N/A', 'Faraway Island', 'None', 219),
        (143, 'Gathering', 'Miner', 'Depths - B1', 'Iron Ore Deposit', 220),
        (143, 'Combat', 'N/A', 'Depths - B2', 'Iron Golem', 221),
        (143, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 222),
        (144, 'Restaurant', 'N/A', 'Faraway Island', 'None', 223),
        (144, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 224),
        (144, 'Tool Shop', 'N/A', 'Ginomorsia', 'None', 225),
        (145, 'Material Shop', 'N/A', 'Faraway Island', 'None', 226),
        (145, 'Restaurant', 'N/A', 'Faraway Island', 'None', 227),
        (132, 'Woodcutting', 'Woodcutter', 'Tropica Isles', 'Water Angeltree', 228),
        (133, 'Woodcutting', 'Woodcutter', 'Lulab Forest', 'Wind Angeltree', 229),
        (134, 'Gathering', 'Angler', 'Treasure Grove', 'Big Fish Shadow', 230),
        (135, 'Gathering', 'Miner', 'Cave of Trials B3', 'Superior Gold Deposit', 231),
        (135, 'Gathering', 'Miner', 'Depths - B2', 'Amazing Gold Deposit', 232),
        (135, 'Combat', 'N/A', 'Treasure Grove', 'Gaia Golem', 233),
        (136, 'Gathering', 'Angler', 'Ginomorsia', 'Eruptuna', 234),
        (137, 'Material Shop', 'N/A', 'Capital of Mysteria', 'None', 235),
        (145, 'Material Shop', 'N/A', 'Lulab Forest', 'None', 236),
        (145, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 237),
        (146, 'Restaurant', 'N/A', 'Faraway Island', 'None', 238),
        (146, 'Gathering', 'Angler', 'Da Finci Cave', 'Small Fish Shadow', 239),
        (147, 'Restaurant', 'N/A', 'Faraway Island', 'None', 240),
        (147, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 241),
        (147, 'Tool Shop', 'N/A', 'Ginomorsia', 'None', 242),
        (148, 'Woodcutting', 'Woodcutter', 'Capital of Mysteria', 'Fire Angeltree', 243),
        (149, 'Woodcutting', 'Woodcutter', 'Capital of Mysteria', 'Fire Angeltree', 244),
        (149, 'Gathering', 'Miner', 'Banaan Cave', 'Fire Starcrystal', 245),
        (149, 'Combat', 'N/A', 'Cave of Trials B4', 'Napdragon', 246),
        (149, 'Combat', 'N/A', 'Depths - B3', 'Mohawkasaurus', 247),
        (150, 'Gathering', 'Miner', 'Banaan Cave', 'Fire Starcrystal', 248),
        (151, 'Material Shop', 'N/A', 'Tropica Isles', 'None', 249),
        (151, 'Material Shop', 'N/A', 'Tropica Isles', 'None', 250),
        (152, 'Gathering', 'Miner', 'Depths - B2', 'Amazing Red Ore Deposit', 251),
        (152, 'Gathering', 'Miner', 'Depths - B3', 'Dragon''s Claw', 252),
        (152, 'Combat', 'N/A', 'Treasure Grove', 'Fortoise', 253),
        (153, 'Combat', 'N/A', 'Depths - B3', 'Mohawkasaurus', 254),
        (154, 'Material Shop', 'N/A', 'Lulab Forest', 'None', 255),
        (154, 'Material Shop', 'N/A', 'Depths - B3', 'None', 256),
        (154, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 257),
        (154, 'Tool Shop', 'N/A', 'Ginomorsia', 'None', 258),
        (155, 'Crafting', 'Farmer', 'Base Camp', 'Kaiser Pumpkin', 259),
        (156, 'Material Shop', 'N/A', 'Tropica Isles', 'None', 260),
        (156, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 261),
        (319, 'Gathering', 'Angler', 'Eternia Village', 'Small Fish Shadow', 262),
        (157, 'Restaurant', 'N/A', 'Tropica Isles', 'None', 263),
        (157, 'Gathering', 'Angler', 'Base Camp', 'Small Fish Shadow', 264),
        (320, 'Material Shop', 'N/A', 'Tropica Isles', 'None', 265),
        (158, 'Gathering', 'Angler', 'Lulab Forest', 'Forest Lordfish', 266),
        (158, 'Material Shop', 'N/A', 'Tropica Isles', 'None', 267),
        (320, 'Material Shop', 'N/A', 'Tropica Isles', 'None', 268),
        (320, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 269),
        (321, 'Crafting', 'Farmer', 'Base Camp', 'Shadow Carrot', 270),
        (321, 'Crafting', 'Farmer', 'Base Camp', 'Wicked Mandrake', 271),
        (159, 'Gathering', 'Angler', 'Lulab Forest', 'Forest Lordfish', 272),
        (321, 'Combat', 'N/A', 'Depths - B1', 'Shadow Carrotella', 273),
        (159, 'Material Shop', 'N/A', 'Tropica Isles', 'None', 274),
        (322, 'Combat', 'N/A', 'Tropica Isles', 'Steel Tortortoise', 275),
        (160, 'Material Shop', 'N/A', 'Faraway Island', 'None', 276),
        (160, 'Material Shop', 'N/A', 'Faraway Island', 'None', 277),
        (322, 'Combat', 'N/A', 'Da Finci Cave', 'Crystal Golem', 278),
        (160, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 279),
        (322, 'Combat', 'N/A', 'Depths - B2', 'Wicked Spooky', 280),
        (160, 'Material Shop', 'N/A', 'Treasure Grove', 'None', 281),
        (323, 'Combat', 'N/A', 'Treasure Grove', 'Shadow Shark', 282),
        (161, 'Material Shop', 'N/A', 'Swolean Island', 'None', 283),
        (323, 'Combat', 'N/A', 'Treasure Grove', 'Shadow Behemoth', 284),
        (161, 'Gathering', 'Miner', 'Depths - B2', 'Ancient Fossil', 285),
        (324, 'Material Shop', 'N/A', 'Swolean Island', 'None', 286),
        (324, 'Combat', 'N/A', 'Depths - B2', 'Cave Panther', 287),
        (324, 'Combat', 'N/A', 'Depths - B2', 'Jackal', 288),
        (325, 'Material Shop', 'N/A', 'Capital of Mysteria', 'None', 289),
        (325, 'Combat', 'N/A', 'Capital of Mysteria', 'White Woolie', 290),
        (325, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 291),
        (325, 'Tool Shop', 'N/A', 'Ginomorsia', 'None', 292),
        (326, 'Combat', 'N/A', 'Treasure Grove', 'King Woolie', 293),
        (327, 'Material Shop', 'N/A', 'Faraway Island', 'None', 294),
        (327, 'Material Shop', 'N/A', 'Treasure Grove', 'None', 295),
        (327, 'Combat', 'N/A', 'Faraway Island', 'Hill Spider', 296),
        (327, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 297),
        (328, 'Combat', 'N/A', 'Ginomorsia', 'Lord of Curses', 298),
        (329, 'Gathering', 'Angler', 'Depths - B3', 'Big Fish Shadow', 299),
        (330, 'Material Shop', 'N/A', 'Swolean Island', 'None', 300),
        (330, 'Woodcutting', 'Woodcutter', 'Cave of Trials', 'Skytree', 301),
        (330, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 302),
        (330, 'Tool Shop', 'N/A', 'Ginomorsia', 'None', 303),
        (331, 'Gathering', 'Angler', 'Depths - B3', 'Small Fish Shadow', 304),
        (332, 'Crafting', 'Farmer', 'Base Camp', 'Pumpkin', 305),
        (332, 'Crafting', 'Farmer', 'Base Camp', 'Kaiser Pumpkin', 306),
        (332, 'Material Shop', 'N/A', 'Lulab Forest', 'None', 307),
        (333, 'Combat', 'N/A', 'Ginomorsia', 'Fiery Panther', 308),
        (333, 'Combat', 'N/A', 'Ginomorsia', 'Pyro Panther', 309),
        (334, 'Combat', 'N/A', 'Ginomorsia', 'Pyro Panther', 310),
        (335, 'Combat', 'N/A', 'Ginomorsia', 'Fiery Panther', 311),
        (335, 'Combat', 'N/A', 'Ginomorsia', 'Pyro Panther', 312),
        (336, 'Material Shop', 'N/A', 'Faraway Island', 'None', 313),
        (336, 'Combat', 'N/A', 'Faraway Island', 'Grass Serpent', 314),
        (336, 'Combat', 'N/A', 'Faraway Island', 'Giant Grass Serpent', 315),
        (336, 'Combat', 'N/A', 'Faraway Island', 'Bloom Serpent', 316),
        (337, 'Restaurant', 'N/A', 'Tropica Isles', 'None', 317),
        (161, 'Combat', 'N/A', 'Ginomorsia', 'Lord of Curses', 318),
        (337, 'Gathering', 'Angler', 'Depths - B2', 'Small Fish Shadow', 319),
        (162, 'Material Shop', 'N/A', 'Ginomorsia', 'None', 320),
        (338, 'Restaurant', 'N/A', 'Tropica Isles', 'None', 321),
        (163, 'Combat', 'N/A', 'Da Finci Cave', 'Crystal Golem', 322),
        (338, 'Gathering', 'Angler', 'Depths - B2', 'Big Fish Shadow', 323),
        (164, 'Crafting', 'Farmer', 'Base Camp', 'Cabbage', 324),
        (339, 'Material Shop', 'N/A', 'Lulab Forest', 'None', 325),
        (164, 'Crafting', 'Farmer', 'Base Camp', 'Godly Cabbage', 326),
        (339, 'Material Shop', 'N/A', 'Depths - B3', 'None', 327),
        (165, 'Combat', 'N/A', 'Depths - B3', 'Bouldergeist', 328),
        (339, 'Combat', 'N/A', 'Lulab Forest', 'Killer Weedling', 329),
        (339, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 330),
        (340, 'Combat', 'N/A', 'Cave of Trials', 'Big Spooky', 331),
        (340, 'Combat', 'N/A', 'Depths - B3', 'Royal Spooky', 332),
        (166, 'Combat', 'N/A', 'Depths - B2', 'Wicked Spooky', 333),
        (340, 'Combat', 'N/A', 'Depths - B3', 'Bouldergeist', 334),
        (167, 'Combat', 'N/A', 'Cave of Trials B2', 'Boor Bear Boss', 335),
        (341, 'Crafting', 'Farmer', 'Base Camp', 'Spooky Spud', 336),
        (167, 'Combat', 'N/A', 'Depths - B3', 'Blizzbear', 337),
        (342, 'Material Shop', 'N/A', 'Lulab Forest', 'None', 338),
        (168, 'Material Shop', 'N/A', 'Faraway Island', 'None', 339),
        (342, 'Restaurant', 'N/A', 'Tropica Isles', 'None', 340),
        (342, 'Combat', 'N/A', 'Faraway Island', 'Applejack Ape', 341),
        (342, 'Combat', 'N/A', 'Lulab Forest', 'Applejack Gorilla', 342),
        (168, 'Combat', 'N/A', 'Faraway Island', 'Giant Grass Serpent', 343),
        (343, 'Combat', 'N/A', 'Da Finci Cave', 'Crystal Golem', 344),
        (168, 'Combat', 'N/A', 'Cave of Trials', 'Greater Rock Serpent', 345),
        (343, 'Combat', 'N/A', 'Cave of Trials', 'Meteoroid', 346),
        (169, 'Combat', 'N/A', 'Lulab Forest', 'Prairie Dragon', 347),
        (343, 'Combat', 'N/A', 'Depths - B3', 'Cave Star', 348),
        (169, 'Combat', 'N/A', 'Cave of Trials B4', 'Napdragon', 349),
        (344, 'Material Shop', 'N/A', 'Swolean Island', 'None', 350),
        (344, 'Woodcutting', 'Woodcutter', 'Depths - B2', 'Starry Tree', 351),
        (344, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 352),
        (344, 'Tool Shop', 'N/A', 'Ginomorsia', 'None', 353),
        (170, 'Crafting', 'Farmer', 'Base Camp', 'Giant Mandrake', 354),
        (345, 'Material Shop', 'N/A', 'Swolean Island', 'None', 355),
        (171, 'Combat', 'N/A', 'Treasure Grove', 'Crystal Behemoth', 356),
        (345, 'Material Shop', 'N/A', 'Treasure Grove', 'None', 357),
        (171, 'Combat', 'N/A', 'Treasure Grove', 'Lord of Death', 358),
        (345, 'Combat', 'N/A', 'Cave of Trials', 'Meteoroid', 359),
        (172, 'Combat', 'N/A', 'Depths - B3', 'Great Chimera', 360),
        (345, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 361),
        (172, 'Combat', 'N/A', 'Treasure Grove', 'Lord of Death', 362),
        (346, 'Material Shop', 'N/A', 'Tropica Isles', 'None', 363),
        (172, 'Combat', 'N/A', 'Treasure Grove', 'Shadow Tyrant', 364),
        (346, 'Combat', 'N/A', 'Tropica Isles', 'Steel Tortortoise', 365),
        (173, 'Combat', 'N/A', 'Treasure Grove', 'Boss Bee', 366),
        (347, 'Material Shop', 'N/A', 'Eternia Village', 'None', 367),
        (347, 'Material Shop', 'N/A', 'Eternia Village', 'None', 368),
        (347, 'Combat', 'N/A', 'Capital of Mysteria', 'Corny', 369),
        (347, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 370),
        (348, 'Material Shop', 'N/A', 'Eternia Village', 'None', 371),
        (348, 'Material Shop', 'N/A', 'Capital of Mysteria', 'None', 372),
        (348, 'Combat', 'N/A', 'Capital of Mysteria', 'Cornella', 373),
        (348, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 374),
        (349, 'Material Shop', 'N/A', 'Tropica Isles', 'None', 375),
        (349, 'Combat', 'N/A', 'Tropica Isles', 'Bitey Shark', 376),
        (349, 'Combat', 'N/A', 'Depths - B2', 'Black Panther', 377),
        (349, 'Combat', 'N/A', 'Cave of Trials', 'Greater Rock Serpent', 378),
        (350, 'Material Shop', 'N/A', 'Tropica Isles', 'None', 379),
        (350, 'Material Shop', 'N/A', 'Tropica Isles', 'None', 380),
        (350, 'Combat', 'N/A', 'Tropica Isles', 'Bitey Shark', 381),
        (174, 'Woodcutting', 'Woodcutter', 'Depths - B3', 'Giant''s Tree', 382),
        (350, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 383),
        (175, 'Woodcutting', 'Woodcutter', 'Depths - B3', 'Giant''s Tree', 384),
        (176, 'Restaurant', 'N/A', 'Swolean Island', 'None', 385),
        (176, 'Material Shop', 'N/A', 'Cave of Trials', 'None', 386),
        (176, 'Material Shop', 'N/A', 'Treasure Grove', 'None', 387),
        (351, 'Material Shop', 'N/A', 'Swolean Island', 'None', 388),
        (177, 'Restaurant', 'N/A', 'Faraway Island', 'None', 389),
        (351, 'Combat', 'N/A', 'Depths - B2', 'Apegore', 390),
        (177, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 391),
        (351, 'Combat', 'N/A', 'Depths - B2', 'Cave Panther', 392),
        (352, 'Gathering', 'Angler', 'Cave of Trials B3', 'Bluescale Lordfish', 393),
        (353, 'Restaurant', 'N/A', 'Faraway Island', 'None', 394),
        (353, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 395),
        (353, 'Tool Shop', 'N/A', 'Ginomorsia', 'None', 396),
        (354, 'Material Shop', 'N/A', 'Tropica Isles', 'None', 397),
        (354, 'Woodcutting', 'Woodcutter', 'Tropica Isles', 'Sugar Tree', 398),
        (354, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 399),
        (354, 'Tool Shop', 'N/A', 'Ginomorsia', 'None', 400),
        (355, 'Material Shop', 'N/A', 'Tropica Isles', 'None', 401),
        (355, 'Woodcutting', 'Woodcutter', 'Tropica Isles', 'Sugar Tree', 402),
        (355, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 403),
        (355, 'Tool Shop', 'N/A', 'Ginomorsia', 'None', 404),
        (356, 'Gathering', 'Miner', 'Treasure Grove', 'Heart of Darkness', 405),
        (357, 'Gathering', 'Miner', 'Treasure Grove', 'Heart of Darkness', 406),
        (177, 'Tool Shop', 'N/A', 'Ginomorsia', 'None', 407),
        (358, 'Combat', 'N/A', 'Depths - B3', 'Stone Golem', 408),
        (358, 'Combat', 'N/A', 'Depths - B3', 'Sand Golem', 409),
        (359, 'Material Shop', 'N/A', 'Tropica Isles', 'None', 410),
        (178, 'Material Shop', 'N/A', 'Treasure Grove', 'None', 411),
        (178, 'Combat', 'N/A', 'Treasure Grove', 'Sandshark', 412),
        (179, 'Material Shop', 'N/A', 'Tropica Isles', 'None', 413),
        (179, 'Combat', 'N/A', 'Da Finci Cave', 'White Runner', 414),
        (180, 'Material Shop', 'N/A', 'Faraway Island', 'None', 415),
        (180, 'Combat', 'N/A', 'Lulab Forest', 'Cashmeer', 416),
        (180, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 417),
        (180, 'Tool Shop', 'N/A', 'Ginomorsia', 'None', 418),
        (181, 'Gathering', 'Angler', 'Treasure Grove', 'Godfish', 419),
        (182, 'Gathering', 'Angler', 'Treasure Grove', 'Godfish', 420),
        (183, 'Crafting', 'Farmer', 'Base Camp', 'Godly Cabbage', 421),
        (359, 'Material Shop', 'N/A', 'Depths - B3', 'None', 422),
        (184, 'Material Shop', 'Angler', 'Da Finci Cave', 'Big Fish Shadow', 423),
        (185, 'Combat', 'N/A', 'Lulab Forest', 'Applejack Gorilla', 424),
        (185, 'Combat', 'N/A', 'Depths - B2', 'Apegore', 425),
        (186, 'Combat', 'N/A', 'Capital of Mysteria', 'Hearhare', 426),
        (186, 'Combat', 'N/A', 'Depths - B2', 'Snowflake Bunny', 427),
        (186, 'Combat', 'N/A', 'Treasure Grove', 'Killer Bunny', 428),
        (187, 'Gathering', 'Angler', 'Tropica Isles', 'Golden Swordfish', 429),
        (188, 'Combat', 'N/A', 'Lulab Forest', 'Goldmeer', 430),
        (189, 'Material Shop', 'N/A', 'Tropica Isles', 'None', 431),
        (189, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 432),
        (359, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 433),
        (359, 'Material Shop', 'N/A', 'Treasure Grove', 'None', 434),
        (360, 'Material Shop', 'N/A', 'Capital of Mysteria', 'None', 435),
        (360, 'Combat', 'N/A', 'Capital of Mysteria', 'Proto Beetle Baller', 436),
        (360, 'Combat', 'N/A', 'Depths - B2', 'Star Beetle Baller', 437),
        (361, 'Restaurant', 'N/A', 'Eternia Village', 'None', 438),
        (361, 'Combat', 'N/A', 'Capital of Mysteria', 'Corny', 439),
        (361, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 440),
        (361, 'Tool Shop', 'N/A', 'Ginomorsia', 'None', 441),
        (190, 'Gathering', 'Angler', 'Tropica Isles', 'Golden Swordfish', 442),
        (362, 'Material Shop', 'N/A', 'Swolean Island', 'None', 443),
        (191, 'Material Shop', 'N/A', 'Lulab Forest', 'None', 444),
        (191, 'Material Shop', 'N/A', 'Ginomorsia - Shroomhaven', 'None', 445),
        (191, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 446),
        (191, 'Tool Shop', 'N/A', 'Ginomorsia', 'None', 447),
        (192, 'Gathering', 'Miner', 'Ginomorsia', 'Golemstone', 448),
        (193, 'Material Shop', 'N/A', 'Faraway Island', 'None', 449),
        (193, 'Gathering', 'Miner', 'Spirit Road', 'Wind Starcrystal', 450),
        (193, 'Gathering', 'Miner', 'Profunda Cave', 'Water Starcrystal', 451),
        (194, 'Crafting', 'Farmer', 'Base Camp', 'Pumpkin', 452),
        (194, 'Crafting', 'Farmer', 'Base Camp', 'Kaiser Pumpkin', 453),
        (195, 'Gathering', 'Angler', 'Treasure Grove', 'Great Lucky Bream', 454),
        (196, 'Combat', 'N/A', 'Lulab Forest', 'Prairie Dragon', 455),
        (362, 'Gathering', 'Miner', 'Cave of Trials', 'Gold Deposit', 456),
        (197, 'Crafting', 'Farmer', 'Base Camp', 'Great Spirit Radish', 457),
        (198, 'Crafting', 'Farmer', 'Base Camp', 'Great Spirit Radish', 458),
        (199, 'Material Shop', 'N/A', 'Lulab Forest', 'None', 459),
        (199, 'Gathering', 'Angler', 'Lulab Forest', 'Small Fish Shadow', 460),
        (200, 'Material Shop', 'N/A', 'Eternia Village', 'None', 461),
        (200, 'Material Shop', 'N/A', 'Capital of Mysteria', 'None', 462),
        (200, 'Combat', 'N/A', 'Eternia Village', 'Tropic Toad', 463),
        (201, 'Material Shop', 'N/A', 'Ginomorsia', 'None', 464),
        (201, 'Combat', 'N/A', 'Ginomorsia', 'Head Haniwa', 465),
        (362, 'Combat', 'N/A', 'Treasure Grove', 'Gaia Golem', 466),
        (362, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 467),
        (363, 'Gathering', 'Angler', 'Tropica Isles', 'Swordfish', 468),
        (363, 'Material Shop', 'N/A', 'Tropica Isles', 'None', 469),
        (364, 'Gathering', 'Angler', 'Tropica Isles', 'Swordfish', 470),
        (364, 'Material Shop', 'N/A', 'Tropica Isles', 'None', 471),
        (365, 'Material Shop', 'N/A', 'Faraway Island', 'None', 472),
        (365, 'Combat', 'N/A', 'Faraway Island', 'Bloom Serpent', 473),
        (365, 'Combat', 'N/A', 'Lulab Forest', 'Forest Panther', 474),
        (202, 'Material Shop', 'Miner', 'Treasure Grove', 'Haniwa Stone', 475),
        (365, 'Combat', 'N/A', 'Depths - B2', 'Black Panther', 476),
        (202, 'Material Shop', 'Miner', 'Treasure Grove', 'Great Haniwa Stone', 477),
        (366, 'Combat', 'N/A', 'Treasure Grove', 'Fortoise', 478),
        (202, 'Combat', 'N/A', 'Ginomorsia', 'Haniwa Tribe', 479),
        (202, 'Tool Shop', 'N/A', 'Ginomorsia', 'None', 480),
        (203, 'Material Shop', 'N/A', 'Tropica Isles', 'None', 481),
        (203, 'Combat', 'N/A', 'Depths - B2', 'Black Panther', 482),
        (203, 'Combat', 'N/A', 'Depths - B2', 'Jackal', 483),
        (203, 'Combat', 'N/A', 'Treasure Grove', 'White Panther', 484),
        (204, 'Material Shop', 'N/A', 'Eternia Village', 'None', 485),
        (366, 'Combat', 'N/A', 'Treasure Grove', 'Shadow Tortortoise', 486),
        (367, 'Restaurant', 'N/A', 'Faraway Island', 'None', 487),
        (367, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 488),
        (367, 'Tool Shop', 'N/A', 'Ginomorsia', 'None', 489),
        (368, 'Material Shop', 'N/A', 'Treasure Grove', 'None', 490),
        (369, 'Gathering', 'Miner', 'Eternia Village', 'Copper Deposit', 491),
        (204, 'Material Shop', 'N/A', 'Eternia Village', 'None', 492),
        (369, 'Combat', 'N/A', 'Depths - B3', 'Sand Golem', 493),
        (204, 'Combat', 'N/A', 'Ginomorsia', 'Crimson Weedling', 494),
        (369, 'Tool Shop', 'N/A', 'Ginomorsia', 'None', 495),
        (204, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 496),
        (370, 'Material Shop', 'N/A', 'Swolean Island', 'None', 497),
        (205, 'Crafting', 'Farmer', 'Base Camp', 'Carrot', 498),
        (370, 'Restaurant', 'N/A', 'Swolean Island', 'None', 499),
        (205, 'Crafting', 'Farmer', 'Base Camp', 'Giant Mandrake', 500),
        (206, 'Gathering', 'Angler', 'Treasure Grove', 'High-Flying Fish', 501),
        (370, 'Material Shop', 'N/A', 'Cave of Trials', 'None', 502),
        (370, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 503),
        (207, 'Gathering', 'Angler', 'Treasure Grove', 'Big Fish Shadow', 504),
        (371, 'Restaurant', 'N/A', 'Tropica Isles', 'None', 505),
        (208, 'Combat', 'N/A', 'Depths - B3', 'Blizzbear', 506),
        (209, 'Gathering', 'Angler', 'Depths - B2', 'Coldwater Tuna', 507),
        (210, 'Crafting', 'Farmer', 'Base Camp', 'Spooky Spud', 508),
        (211, 'Crafting', 'Farmer', 'Base Camp', 'Armored Onion', 509),
        (212, 'Restaurant', 'N/A', 'Tropica Isles', 'None', 510),
        (212, 'Material Shop', 'N/A', 'Treasure Grove', 'None', 511),
        (212, 'Combat', 'N/A', 'Ginomorsia', 'Burly Gorilla', 512),
        (212, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 513),
        (213, 'Material Shop', 'N/A', 'Treasure Grove', 'None', 514),
        (213, 'Combat', 'N/A', 'Ginomorsia', 'Burly Gorilla', 515),
        (371, 'Gathering', 'Angler', 'Base Camp', 'Big Fish Shadow', 516),
        (372, 'Material Shop', 'N/A', 'Tropica Isles', 'None', 517),
        (372, 'Restaurant', 'N/A', 'Tropica Isles', 'None', 518),
        (372, 'Material Shop', 'N/A', 'Tropica Isles', 'None', 519),
        (372, 'Combat', 'N/A', 'Depths - B2', 'Greater Sea Beetle Baller', 520),
        (373, 'Material Shop', 'N/A', 'Tropica Isles', 'None', 521),
        (373, 'Gathering', 'Miner', 'Tropica Isles', 'Silver Ore Deposit', 522),
        (373, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 523),
        (373, 'Tool Shop', 'N/A', 'Ginomorsia', 'None', 524),
        (213, 'Tool Shop', 'N/A', 'Ginomorsia', 'None', 525),
        (213, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 526),
        (214, 'Crafting', 'Farmer', 'Base Camp', 'Kaiser Pumpkin', 527),
        (374, 'Material Shop', 'N/A', 'Lulab Forest', 'None', 528),
        (215, 'Restaurant', 'N/A', 'Tropica Isles', 'None', 529),
        (374, 'Material Shop', 'N/A', 'Lulab Forest', 'None', 530),
        (215, 'Gathering', 'Angler', 'Base Camp', 'Small Fish Shadow', 531),
        (374, 'Material Shop', 'N/A', 'Treasure Grove', 'None', 532),
        (375, 'Restaurant', 'N/A', 'Capital of Mysteria', 'None', 533),
        (375, 'Gathering', 'Angler', 'Base Camp', 'Big Fish Shadow', 534),
        (216, 'Gathering', 'Angler', 'Ginomorsia', 'Small Fish Shadow', 535),
        (376, 'Restaurant', 'N/A', 'Eternia Village', 'None', 536),
        (217, 'Material Shop', 'N/A', 'Capital of Mysteria', 'None', 537),
        (376, 'Restaurant', 'N/A', 'Capital of Mysteria', 'None', 538),
        (217, 'Material Shop', 'N/A', 'Faraway Island', 'None', 539),
        (217, 'Combat', 'N/A', 'Depths - B3', 'Pandora''s Box', 540),
        (217, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 541),
        (218, 'Woodcutting', 'Woodcutter', 'Ginomorsia', 'Legendary God Tree', 542),
        (219, 'Combat', 'N/A', 'Ginomorsia', 'Legendary Don Woolie', 543),
        (220, 'Combat', 'N/A', 'Ginomorsia', 'Legendary Don Woolie', 544),
        (221, 'Crafting', 'Farmer', 'Ginomorsia', 'Legendary King Spud', 545),
        (222, 'Gathering', 'Angler', 'Ginomorsia', 'Legendary Rocket Fish', 546),
        (223, 'Gathering', 'Miner', 'Ginomorsia', 'Legendary Shiny Geode', 547),
        (224, 'Material Shop', 'N/A', 'Swolean Island', 'None', 548),
        (224, 'Combat', 'N/A', 'Depths - B2', 'Iron Golem', 549),
        (376, 'Gathering', 'Angler', 'Base Camp', 'Small Fish Shadow', 550),
        (377, 'Material Shop', 'N/A', 'Capital of Mysteria', 'None', 551),
        (377, 'Combat', 'N/A', 'Capital of Mysteria', 'Tortortoise', 552),
        (224, 'Combat', 'N/A', 'Depths - B3', 'Bouldergeist', 553),
        (225, 'Material Shop', 'N/A', 'Lulab Forest', 'None', 554),
        (225, 'Material Shop', 'N/A', 'Depths - B3', 'None', 555),
        (225, 'Combat', 'N/A', 'Lulab Forest', 'Weedling', 556),
        (225, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 557),
        (226, 'Combat', 'N/A', 'Capital of Mysteria', 'Tunoco Quetzal', 558),
        (226, 'Combat', 'N/A', 'Lulab Forest', 'Prairie Dragon', 559),
        (226, 'Combat', 'N/A', 'Cave of Trials B4', 'Napdragon', 560),
        (227, 'Material Shop', 'N/A', 'Eternia Village', 'None', 561),
        (378, 'Restaurant', 'N/A', 'Swolean Island', 'None', 562),
        (378, 'Combat', 'N/A', 'Depths - B3', 'Wild Buffalo', 563),
        (379, 'Material Shop', 'N/A', 'Depths - B3', 'None', 564),
        (379, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 565),
        (379, 'Material Shop', 'N/A', 'Treasure Grove', 'None', 566),
        (380, 'Material Shop', 'N/A', 'Tropica Isles', 'None', 567),
        (380, 'Material Shop', 'N/A', 'Tropica Isles', 'None', 568),
        (380, 'Combat', 'N/A', 'Depths - B3', 'Cave Star', 569),
        (380, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 570),
        (381, 'Restaurant', 'N/A', 'Tropica Isles', 'None', 571),
        (227, 'Material Shop', 'N/A', 'Eternia Village', 'None', 572),
        (227, 'Combat', 'N/A', 'Tropica Isles', 'Stelleroid', 573),
        (227, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 574),
        (228, 'Material Shop', 'N/A', 'Eternia Village', 'None', 575),
        (228, 'Material Shop', 'N/A', 'Capital of Mysteria', 'None', 576),
        (228, 'Combat', 'N/A', 'Eternia Village', 'Tunoco Lizard', 577),
        (228, 'Combat', 'N/A', 'Tropica Isles', 'Sandzard', 578),
        (229, 'Gathering', 'Angler', 'Treasure Grove', 'Great Lucky Bream', 579),
        (230, 'Restaurant', 'N/A', 'Faraway Island', 'None', 580),
        (381, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 581),
        (381, 'Tool Shop', 'N/A', 'Ginomorsia', 'None', 582),
        (230, 'Gathering', 'Angler', 'Base Camp', 'Small Fish Shadow', 583),
        (382, 'Material Shop', 'N/A', 'Tropica Isles', 'None', 584),
        (231, 'Gathering', 'Miner', 'Treasure Grove', 'Magic Ore Deposit', 585),
        (382, 'Material Shop', 'N/A', 'Depths - B3', 'None', 586),
        (231, 'Gathering', 'Miner', 'Treasure Grove', 'Great Magic Ore Deposit', 587),
        (382, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 588),
        (231, 'Gathering', 'Miner', 'Treasure Grove', 'Luminous Magic Ore Deposit', 589),
        (382, 'Material Shop', 'N/A', 'Treasure Grove', 'None', 590),
        (383, 'Material Shop', 'N/A', 'Eternia Village', 'None', 591),
        (383, 'Material Shop', 'N/A', 'Eternia Village', 'None', 592),
        (383, 'Combat', 'N/A', 'Ginomorsia', 'Crimson Weedling', 593),
        (383, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 594),
        (384, 'Material Shop', 'N/A', 'Faraway Island', 'None', 595),
        (384, 'Woodcutting', 'Woodcutter', 'Faraway Island', 'Pine Tree', 596),
        (384, 'Woodcutting', 'Woodcutter', 'Cave of Trials', 'Skytree', 597),
        (384, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 598),
        (385, 'Woodcutting', 'Woodcutter', 'Tropica Isles', 'Water Angeltree', 599),
        (232, 'Material Shop', 'N/A', 'Tropica Isles', 'None', 600),
        (386, 'Woodcutting', 'Woodcutter', 'Tropica Isles', 'Water Angeltree', 601),
        (232, 'Combat', 'N/A', 'Depths - B2', 'Wicked Spooky', 602),
        (232, 'Combat', 'N/A', 'Depths - B2', 'Greater Sea Beetle Baller', 603),
        (232, 'Combat', 'N/A', 'Cave of Trials', 'Mini Spooky', 604),
        (233, 'Gathering', 'Miner', 'Depths - B3', 'Dragon''s Claw', 605),
        (234, 'Gathering', 'Angler', 'Ginomorsia', 'Eruptuna', 606),
        (386, 'Gathering', 'Miner', 'Profunda Cave', 'Water Starcrystal', 607),
        (386, 'Combat', 'N/A', 'Da Finci Cave', 'Crystal Golem', 608),
        (386, 'Combat', 'N/A', 'Depths - B3', 'Blizzbear', 609),
        (387, 'Gathering', 'Miner', 'Profunda Cave', 'Water Starcrystal', 610),
        (235, 'Gathering', 'Miner', 'Depths - B2', 'Superior Red Ore Deposit', 611),
        (388, 'Material Shop', 'N/A', 'Tropica Isles', 'None', 612),
        (235, 'Gathering', 'Miner', 'Depths - B3', 'Dragon''s Claw', 613),
        (388, 'Combat', 'N/A', 'Depths - B2', 'Greater Sea Beetle Baller', 614),
        (235, 'Gathering', 'Miner', 'Ginomorsia', 'Golemstone', 615),
        (388, 'Combat', 'N/A', 'Depths - B2', 'Greater Beetle Baller', 616),
        (389, 'Material Shop', 'N/A', 'Tropica Isles', 'None', 617),
        (235, 'Combat', 'N/A', 'Treasure Grove', 'Fortoise', 618),
        (236, 'Gathering', 'Miner', 'Profunda Cave', 'Superior Marine Ore Deposit', 619),
        (236, 'Gathering', 'Miner', 'Profunda Cave', 'Amazing Marine Ore Deposit', 620),
        (236, 'Gathering', 'Miner', 'Profunda Cave', 'Water Starcrystal', 621),
        (237, 'Material Shop', 'N/A', 'Treasure Grove', 'None', 622),
        (237, 'Combat', 'N/A', 'Depths - B3', 'Cave Star', 623),
        (238, 'Material Shop', 'N/A', 'Faraway Island', 'None', 624),
        (238, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 625),
        (389, 'Material Shop', 'N/A', 'Spirit Road', 'None', 626),
        (239, 'Restaurant', 'N/A', 'Eternia Village', 'None', 627),
        (389, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 628),
        (239, 'Restaurant', 'N/A', 'Capital of Mysteria', 'None', 629),
        (389, 'Tool Shop', 'N/A', 'Ginomorsia', 'None', 630),
        (390, 'Material Shop', 'N/A', 'Capital of Mysteria', 'None', 631),
        (391, 'Crafting', 'Farmer', 'Base Camp', 'Wicked Mandrake', 632),
        (239, 'Combat', 'N/A', 'Cave of Trials B1', 'Buffalo', 633),
        (239, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 634),
        (240, 'Material Shop', 'N/A', 'Eternia Village', 'None', 635),
        (392, 'Combat', 'N/A', 'Treasure Grove', 'King Woolie', 636),
        (393, 'Combat', 'N/A', 'Cave of Trials B4', 'Taurus', 637),
        (393, 'Tool Shop', 'N/A', 'Ginomorsia', 'None', 638),
        (394, 'Combat', 'N/A', 'Cave of Trials B4', 'Taurus', 639),
        (394, 'Combat', 'N/A', 'Depths - B3', 'Wild Buffalo', 640),
        (240, 'Gathering', 'Miner', 'Eternia Village', 'Copper Deposit', 641),
        (394, 'Tool Shop', 'N/A', 'Ginomorsia', 'None', 642),
        (395, 'Restaurant', 'N/A', 'Swolean Island', 'None', 643),
        (395, 'Material Shop', 'N/A', 'Treasure Grove', 'None', 644),
        (395, 'Combat', 'N/A', 'Ginomorsia', 'Burly Gorilla', 645),
        (395, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 646),
        (396, 'Woodcutting', 'Woodcutter', 'Lulab Forest', 'Wind Angeltree', 647),
        (397, 'Woodcutting', 'Woodcutter', 'Lulab Forest', 'Wind Angeltree', 648),
        (397, 'Gathering', 'Miner', 'Spirit Road', 'Wind Starcrystal', 649),
        (397, 'Crafting', 'Farmer', 'Spirit Road', 'Giant Mandrake', 650),
        (397, 'Combat', 'N/A', 'Depths - B3', 'Great Chimera', 651),
        (401, 'Material Shop', 'N/A', 'Faraway Island', 'None', 652),
        (401, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 653),
        (398, 'Gathering', 'Miner', 'Spirit Road', 'Wind Starcrystal', 654),
        (399, 'Material Shop', 'N/A', 'Faraway Island', 'None', 655),
        (401, 'Tool Shop', 'N/A', 'Ginomorsia', 'None', 656),
        (402, 'Material Shop', 'N/A', 'Capital of Mysteria', 'None', 657),
        (402, 'Combat', 'N/A', 'Eternia Village', 'Tropic Toad', 658),
        (403, 'Material Shop', 'N/A', 'Eternia Village', 'None', 659),
        (403, 'Gathering', 'Miner', 'Eternia Village', 'Copper Deposit', 660),
        (403, 'Combat', 'N/A', 'Depths - B3', 'Gemeleon', 661),
        (403, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 662),
        (419, 'Crafting', 'Carpenter', 'N/A', 'None', 663),
        (420, 'Crafting', 'Carpenter', 'N/A', 'None', 664),
        (421, 'Crafting', 'Carpenter', 'N/A', 'None', 665),
        (422, 'Crafting', 'Carpenter', 'N/A', 'None', 666),
        (423, 'Crafting', 'Carpenter', 'N/A', 'None', 667),
        (423, 'Material Shop', 'N/A', 'Faraway Island', 'None', 668),
        (423, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 669),
        (423, 'Tool Shop', 'N/A', 'Ginomorsia', 'None', 670),
        (424, 'Crafting', 'Carpenter', 'N/A', 'None', 671),
        (425, 'Crafting', 'Carpenter', 'N/A', 'None', 672),
        (425, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 673),
        (426, 'Crafting', 'Carpenter', 'N/A', 'None', 674),
        (426, 'Tool Shop', 'N/A', 'Ginomorsia', 'None', 675),
        (427, 'Crafting', 'Carpenter', 'N/A', 'None', 676),
        (428, 'Crafting', 'Carpenter', 'N/A', 'None', 677),
        (429, 'Crafting', 'Carpenter', 'N/A', 'None', 678),
        (399, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 679),
        (430, 'Crafting', 'Carpenter', 'N/A', 'None', 680),
        (400, 'Material Shop', 'N/A', 'Eternia Village', 'None', 681),
        (431, 'Crafting', 'Carpenter', 'N/A', 'None', 682),
        (400, 'Material Shop', 'N/A', 'Capital of Mysteria', 'None', 683),
        (431, 'Material Shop', 'N/A', 'Eternia Village', 'None', 684),
        (400, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 685),
        (431, 'Material Shop', 'N/A', 'Capital of Mysteria', 'None', 686),
        (401, 'Material Shop', 'N/A', 'Faraway Island', 'None', 687),
        (431, 'Tool Shop', 'N/A', 'Ginomorsia', 'None', 688),
        (432, 'Crafting', 'Carpenter', 'N/A', 'None', 689),
        (433, 'Crafting', 'Carpenter', 'N/A', 'None', 690),
        (434, 'Crafting', 'Carpenter', 'N/A', 'None', 691),
        (434, 'Material Shop', 'N/A', 'Eternia Village', 'None', 692),
        (434, 'Material Shop', 'N/A', 'Capital of Mysteria', 'None', 693),
        (434, 'Tool Shop', 'N/A', 'Ginomorsia', 'None', 694),
        (435, 'Crafting', 'Carpenter', 'N/A', 'None', 695),
        (435, 'Material Shop', 'N/A', 'Faraway Island', 'None', 696),
        (435, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 697),
        (435, 'Tool Shop', 'N/A', 'Ginomorsia', 'None', 698),
        (436, 'Crafting', 'Carpenter', 'N/A', 'None', 699),
        (437, 'Crafting', 'Carpenter', 'N/A', 'None', 700),
        (438, 'Crafting', 'Carpenter', 'N/A', 'None', 701),
        (439, 'Crafting', 'Carpenter', 'N/A', 'None', 702),
        (439, 'Material Shop', 'N/A', 'Swolean Island', 'None', 703),
        (439, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 704),
        (439, 'Tool Shop', 'N/A', 'Ginomorsia', 'None', 705),
        (440, 'Crafting', 'Carpenter', 'N/A', 'None', 706),
        (441, 'Crafting', 'Carpenter', 'N/A', 'None', 707),
        (441, 'Material Shop', 'N/A', 'Swolean Island', 'None', 708),
        (441, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 709),
        (441, 'Tool Shop', 'N/A', 'Ginomorsia', 'None', 710),
        (442, 'Crafting', 'Carpenter', 'N/A', 'None', 711),
        (442, 'Material Shop', 'N/A', 'Tropica Isles', 'None', 712),
        (442, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 713),
        (442, 'Tool Shop', 'N/A', 'Ginomorsia', 'None', 714),
        (443, 'Crafting', 'Carpenter', 'N/A', 'None', 715),
        (444, 'Crafting', 'Carpenter', 'N/A', 'None', 716),
        (445, 'Crafting', 'Tailor', 'N/A', 'None', 717),
        (445, 'Material Shop', 'N/A', 'Capital of Mysteria', 'None', 718),
        (445, 'Tool Shop', 'N/A', 'Ginomorsia', 'None', 719),
        (446, 'Crafting', 'Tailor', 'N/A', 'None', 720),
        (446, 'Material Shop', 'N/A', 'Faraway Island', 'None', 721),
        (446, 'Tool Shop', 'N/A', 'Ginomorsia', 'None', 722),
        (447, 'Crafting', 'Tailor', 'N/A', 'None', 723),
        (447, 'Material Shop', 'N/A', 'Eternia Village', 'None', 724),
        (447, 'Material Shop', 'N/A', 'Capital of Mysteria', 'None', 725),
        (447, 'Tool Shop', 'N/A', 'Ginomorsia', 'None', 726),
        (448, 'Crafting', 'Tailor', 'N/A', 'None', 727),
        (449, 'Crafting', 'Tailor', 'N/A', 'None', 728),
        (449, 'Material Shop', 'N/A', 'Lulab Forest', 'None', 729),
        (449, 'Tool Shop', 'N/A', 'Ginomorsia', 'None', 730),
        (450, 'Crafting', 'Tailor', 'N/A', 'None', 731),
        (451, 'Crafting', 'Tailor', 'N/A', 'None', 732),
        (452, 'Crafting', 'Tailor', 'N/A', 'None', 733),
        (452, 'Material Shop', 'N/A', 'Faraway Island', 'None', 734),
        (452, 'Tool Shop', 'N/A', 'Ginomorsia', 'None', 735),
        (453, 'Crafting', 'Tailor', 'N/A', 'None', 736),
        (453, 'Material Shop', 'N/A', 'Swolean Island', 'None', 737),
        (454, 'Crafting', 'Tailor', 'N/A', 'None', 738),
        (454, 'Material Shop', 'N/A', 'Tropica Isles', 'None', 739),
        (455, 'Crafting', 'Tailor', 'N/A', 'None', 740),
        (455, 'Material Shop', 'N/A', 'Capital of Mysteria', 'None', 741),
        (455, 'Tool Shop', 'N/A', 'Ginomorsia', 'None', 742),
        (456, 'Crafting', 'Tailor', 'N/A', 'None', 743),
        (456, 'Material Shop', 'N/A', 'Eternia Village', 'None', 744),
        (456, 'Material Shop', 'N/A', 'Capital of Mysteria', 'None', 745),
        (456, 'Tool Shop', 'N/A', 'Ginomorsia', 'None', 746),
        (457, 'Crafting', 'Tailor', 'N/A', 'None', 747),
        (458, 'Crafting', 'Tailor', 'N/A', 'None', 748),
        (459, 'Crafting', 'Carpenter', 'N/A', 'None', 749),
        (460, 'Crafting', 'Carpenter', 'N/A', 'None', 750),
        (461, 'Crafting', 'Blacksmith', 'N/A', 'None', 751),
        (461, 'Material Shop', 'N/A', 'Eternia Village', 'None', 752),
        (461, 'Material Shop', 'N/A', 'Capital of Mysteria', 'None', 753),
        (461, 'Tool Shop', 'N/A', 'Ginomorsia', 'None', 754),
        (462, 'Crafting', 'Blacksmith', 'N/A', 'None', 755),
        (462, 'Material Shop', 'N/A', 'Faraway Island', 'None', 756),
        (462, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 757),
        (462, 'Tool Shop', 'N/A', 'Ginomorsia', 'None', 758),
        (463, 'Crafting', 'Blacksmith', 'N/A', 'None', 759),
        (463, 'Material Shop', 'N/A', 'Tropica Isles', 'None', 760),
        (463, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 761),
        (463, 'Tool Shop', 'N/A', 'Ginomorsia', 'None', 762),
        (464, 'Crafting', 'Blacksmith', 'N/A', 'None', 763),
        (465, 'Crafting', 'Blacksmith', 'N/A', 'None', 764),
        (465, 'Material Shop', 'N/A', 'Swolean Island', 'None', 765),
        (465, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 766),
        (465, 'Tool Shop', 'N/A', 'Ginomorsia', 'None', 767),
        (466, 'Crafting', 'Blacksmith', 'N/A', 'None', 768),
        (466, 'Material Shop', 'N/A', 'Swolean Island', 'None', 769),
        (466, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 770),
        (466, 'Tool Shop', 'N/A', 'Ginomorsia', 'None', 771),
        (467, 'Crafting', 'Blacksmith', 'N/A', 'None', 772),
        (468, 'Crafting', 'Blacksmith', 'N/A', 'None', 773),
        (469, 'Crafting', 'Blacksmith', 'N/A', 'None', 774),
        (470, 'Crafting', 'Blacksmith', 'N/A', 'None', 775),
        (471, 'Crafting', 'Blacksmith', 'N/A', 'None', 776),
        (472, 'Crafting', 'Blacksmith', 'N/A', 'None', 777),
        (473, 'Crafting', 'Blacksmith', 'N/A', 'None', 778),
        (475, 'Crafting', 'Blacksmith', 'N/A', 'None', 779),
        (476, 'Crafting', 'Blacksmith', 'N/A', 'None', 780),
        (477, 'Crafting', 'Blacksmith', 'N/A', 'None', 781),
        (478, 'Crafting', 'Blacksmith', 'N/A', 'None', 782),
        (479, 'Crafting', 'Blacksmith', 'N/A', 'None', 783),
        (480, 'Crafting', 'Blacksmith', 'N/A', 'None', 784),
        (481, 'Crafting', 'Blacksmith', 'N/A', 'None', 785),
        (482, 'Crafting', 'Blacksmith', 'N/A', 'None', 786),
        (483, 'Crafting', 'Blacksmith', 'N/A', 'None', 787),
        (484, 'Crafting', 'Blacksmith', 'N/A', 'None', 788),
        (485, 'Crafting', 'Blacksmith', 'N/A', 'None', 789),
        (486, 'Crafting', 'Alchemist', 'N/A', 'None', 790),
        (487, 'Crafting', 'Alchemist', 'N/A', 'None', 791),
        (487, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 792),
        (488, 'Crafting', 'Alchemist', 'N/A', 'None', 793),
        (488, 'Tool Shop', 'N/A', 'Tropica Isles', 'None', 794),
        (488, 'Tool Shop', 'N/A', 'Swolean Island', 'None', 795),
        (489, 'Crafting', 'Alchemist', 'N/A', 'None', 796),
        (489, 'Tool Shop', 'N/A', 'Eternia Village', 'None', 797),
        (489, 'Tool Shop', 'N/A', 'Capital of Mysteria', 'None', 798),
        (489, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 799),
        (490, 'Crafting', 'Alchemist', 'N/A', 'None', 800),
        (490, 'Tool Shop', 'N/A', 'Faraway Island', 'None', 801),
        (490, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 802),
        (491, 'Crafting', 'Alchemist', 'N/A', 'None', 803),
        (491, 'Tool Shop', 'N/A', 'Tropica Isles', 'None', 804),
        (491, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 805),
        (492, 'Crafting', 'Artist', 'N/A', 'None', 806),
        (493, 'Crafting', 'Alchemist', 'N/A', 'None', 807),
        (493, 'Tool Shop', 'N/A', 'Tropica Isles', 'None', 808),
        (493, 'Tool Shop', 'N/A', 'Swolean Island', 'None', 809),
        (493, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 810),
        (495, 'Crafting', 'Alchemist', 'N/A', 'None', 811),
        (495, 'Tool Shop', 'N/A', 'Tropica Isles', 'None', 812),
        (495, 'Tool Shop', 'N/A', 'Swolean Island', 'None', 813),
        (495, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 814),
        (496, 'Crafting', 'Alchemist', 'N/A', 'None', 815),
        (496, 'Tool Shop', 'N/A', 'Faraway Island', 'None', 816),
        (496, 'Tool Shop', 'N/A', 'Tropica Isles', 'None', 817),
        (496, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 818),
        (497, 'Crafting', 'Alchemist', 'N/A', 'None', 819),
        (498, 'Crafting', 'Alchemist', 'N/A', 'None', 820),
        (499, 'Crafting', 'Alchemist', 'N/A', 'None', 821),
        (499, 'Tool Shop', 'N/A', 'Tropica Isles', 'None', 822),
        (499, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 823),
        (500, 'Crafting', 'Alchemist', 'N/A', 'None', 824),
        (501, 'Crafting', 'Alchemist', 'N/A', 'None', 825),
        (501, 'Tool Shop', 'N/A', 'Tropica Isles', 'None', 826),
        (501, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 827),
        (1, 'Material Shop', 'N/A', 'Capital of Mysteria', 'None', 828),
        (1, 'Material Shop', 'N/A', 'Capital of Mysteria', 'None', 829),
        (1, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 830),
        (1, 'Tool Shop', 'N/A', 'Ginomorsia', 'None', 831),
        (2, 'Gathering', 'Miner', 'Profunda Cave', 'Superior Marine Ore Deposit', 832),
        (2, 'Gathering', 'Miner', 'Profunda Cave', 'Amazing Marine Ore Deposit', 833),
        (2, 'Combat', 'N/A', 'Treasure Grove', 'Great Gemeleon', 834),
        (3, 'Material Shop', 'N/A', 'Treasure Grove', 'None', 835),
        (3, 'Combat', 'N/A', 'Treasure Grove', 'Sandshark', 836),
        (4, 'Combat', 'N/A', 'Depths - B3', 'Stone Golem', 837),
        (5, 'Gathering', 'Miner', 'Depths - B3', 'Giant Ancient Fossil', 838),
        (5, 'Gathering', 'Miner', 'Depths - B3', 'Graphite Deposit', 839),
        (5, 'Gathering', 'Miner', 'Depths - B3', 'Dragon''s Claw', 840),
        (6, 'Combat', 'N/A', 'Depths - B3', 'Stone Golem', 841),
        (7, 'Gathering', 'Miner', 'Depths - B3', 'Graphite Deposit', 842),
        (8, 'Restaurant', 'N/A', 'Tropica Isles', 'None', 843),
        (8, 'Gathering', 'Angler', 'Tropica Isles', 'Big Fish Shadow', 844),
        (9, 'Material Shop', 'N/A', 'Lulab Forest', 'None', 845),
        (9, 'Combat', 'N/A', 'Lulab Forest', 'Forest Panther', 846),
        (9, 'Combat', 'N/A', 'Depths - B2', 'Black Panther', 847),
        (9, 'Combat', 'N/A', 'Depths - B3', 'Grotto Wolf', 848),
        (10, 'Material Shop', 'N/A', 'Capital of Mysteria', 'None', 849),
        (10, 'Combat', 'N/A', 'Capital of Mysteria', 'Hearhare', 850),
        (10, 'Combat', 'N/A', 'Depths - B2', 'Snowflake Bunny', 851),
        (10, 'Combat', 'N/A', 'Treasure Grove', 'Killer Bunny', 852),
        (11, 'Material Shop', 'N/A', 'Capital of Mysteria', 'None', 853),
        (11, 'Combat', 'N/A', 'Capital of Mysteria', 'Red Wolf', 854),
        (11, 'Combat', 'N/A', 'Faraway Island', 'Grass Serpent', 855),
        (11, 'Combat', 'N/A', 'Cave of Trials', 'Cave Bat', 856),
        (12, 'Material Shop', 'N/A', 'Capital of Mysteria', 'None', 857),
        (12, 'Combat', 'N/A', 'Capital of Mysteria', 'Red Wolf', 858),
        (12, 'Combat', 'N/A', 'Lulab Forest', 'Cashmeer', 859),
        (12, 'Combat', 'N/A', 'Cave of Trials B1', 'Buffalo', 860),
        (13, 'Gathering', 'Angler', 'Depths - B3', 'Deep Sea Lordfish', 861),
        (14, 'Material Shop', 'N/A', 'Eternia Village', 'None', 862),
        (14, 'Woodcutting', 'Woodcutter', 'Eternia Village', 'Oak Tree', 863),
        (14, 'Combat', 'N/A', 'Lulab Forest', 'Pseudo Oak', 864),
        (14, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 865),
        (15, 'Material Shop', 'N/A', 'Faraway Island', 'None', 866),
        (15, 'Woodcutting', 'Woodcutter', 'Faraway Island', 'Cherry Tree', 867),
        (15, 'Woodcutting', 'Woodcutter', 'Depths - B2', 'Starry Tree', 868),
        (15, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 869),
        (16, 'Crafting', 'Artist', 'N/A', 'None', 870),
        (16, 'Material Shop', 'N/A', 'Tropica Isles', 'None', 871),
        (16, 'Tool Shop', 'N/A', 'Ginomorsia', 'None', 872),
        (17, 'Crafting', 'Artist', 'N/A', 'None', 873),
        (17, 'Material Shop', 'N/A', 'Tropica Isles', 'None', 874),
        (17, 'Tool Shop', 'N/A', 'Ginomorsia', 'None', 875),
        (18, 'Crafting', 'Artist', 'N/A', 'None', 876),
        (18, 'Material Shop', 'N/A', 'Tropica Isles', 'None', 877),
        (18, 'Tool Shop', 'N/A', 'Ginomorsia', 'None', 878),
        (19, 'Crafting', 'Artist', 'N/A', 'None', 879),
        (19, 'Material Shop', 'N/A', 'Tropica Isles', 'None', 880),
        (19, 'Tool Shop', 'N/A', 'Ginomorsia', 'None', 881),
        (20, 'Crafting', 'Artist', 'N/A', 'None', 882),
        (20, 'Material Shop', 'N/A', 'Swolean Island', 'None', 883),
        (20, 'Tool Shop', 'N/A', 'Ginomorsia', 'None', 884),
        (21, 'Crafting', 'Artist', 'N/A', 'None', 885),
        (21, 'Material Shop', 'N/A', 'Swolean Island', 'None', 886),
        (21, 'Tool Shop', 'N/A', 'Ginomorsia', 'None', 887),
        (22, 'Crafting', 'Artist', 'N/A', 'None', 888),
        (23, 'Crafting', 'Artist', 'N/A', 'None', 889),
        (24, 'Crafting', 'Artist', 'N/A', 'None', 890),
        (25, 'Crafting', 'Cook', 'N/A', 'None', 891),
        (25, 'Restaurant', 'N/A', 'Eternia Village', 'None', 892),
        (25, 'Restaurant', 'N/A', 'Capital of Mysteria', 'None', 893),
        (26, 'Crafting', 'Cook', 'N/A', 'None', 894),
        (27, 'Crafting', 'Cook', 'N/A', 'None', 895),
        (28, 'Crafting', 'Cook', 'N/A', 'None', 896),
        (29, 'Crafting', 'Cook', 'N/A', 'None', 897),
        (29, 'Restaurant', 'N/A', 'Swolean Island', 'None', 898),
        (30, 'Crafting', 'Cook', 'N/A', 'None', 899),
        (31, 'Crafting', 'Cook', 'N/A', 'None', 900),
        (32, 'Crafting', 'Cook', 'N/A', 'None', 901),
        (34, 'Gathering', 'Miner', 'Depths - B1', 'Iron Ore Deposit', 902),
        (34, 'Gathering', 'Miner', 'Depths - B1', 'Great Iron Ore Deposit', 903),
        (34, 'Combat', 'N/A', 'Depths - B2', 'Iron Golem', 904),
        (34, 'Combat', 'N/A', 'Treasure Grove', 'Great Gemeleon', 905),
        (35, 'Material Shop', 'N/A', 'Lulab Forest', 'None', 906),
        (35, 'Material Shop', 'N/A', 'Faraway Island', 'None', 907),
        (35, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 908),
        (35, 'Tool Shop', 'N/A', 'Ginomorsia', 'None', 909),
        (36, 'Crafting', 'Farmer', 'Base Camp', 'Armored Onion', 910),
        (37, 'Restaurant', 'N/A', 'Faraway Island', 'None', 911),
        (37, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 912),
        (37, 'Tool Shop', 'N/A', 'Ginomorsia', 'None', 913),
        (38, 'Gathering', 'Angler', 'Tropica Isles', 'Bass of Darkness', 914),
        (38, 'Material Shop', 'N/A', 'Tropica Isles', 'None', 915),
        (39, 'Material Shop', 'N/A', 'Treasure Grove', 'None', 916),
        (39, 'Combat', 'N/A', 'Ginomorsia', 'Burly Gorilla', 917),
        (39, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 918),
        (39, 'Tool Shop', 'N/A', 'Ginomorsia', 'None', 919),
        (40, 'Material Shop', 'N/A', 'Faraway Island', 'None', 920),
        (40, 'Combat', 'N/A', 'Lulab Forest', 'Forest Panther', 921),
        (40, 'Combat', 'N/A', 'Tropica Isles', 'Sandzard', 922),
        (40, 'Combat', 'N/A', 'Da Finci Cave', 'Greater Sandzard', 923),
        (41, 'Restaurant', 'N/A', 'Eternia Village', 'None', 924),
        (41, 'Combat', 'N/A', 'Cave of Trials B1', 'Buffalo', 925),
        (41, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 926),
        (41, 'Tool Shop', 'N/A', 'Ginomorsia', 'None', 927),
        (42, 'Gathering', 'Angler', 'Treasure Grove', 'Beelzebub Tuna', 928),
        (43, 'Restaurant', 'N/A', 'Swolean Island', 'None', 929),
        (43, 'Material Shop', 'N/A', 'Depths - B2', 'None', 930),
        (43, 'Material Shop', 'N/A', 'Treasure Grove', 'None', 931),
        (44, 'Material Shop', 'N/A', 'Tropica Isles', 'None', 932),
        (44, 'Combat', 'N/A', 'Da Finci Cave', 'Greater Sandzard', 933),
        (44, 'Combat', 'N/A', 'Treasure Grove', 'Gemeleon', 934),
        (44, 'Combat', 'N/A', 'Treasure Grove', 'Crystal Behemoth', 935),
        (45, 'Combat', 'N/A', 'Treasure Grove', 'Bigbeak', 936),
        (46, 'Material Shop', 'N/A', 'Swolean Island', 'None', 937),
        (46, 'Material Shop', 'N/A', 'Spirit Road', 'None', 938),
        (46, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 939),
        (46, 'Tool Shop', 'N/A', 'Ginomorsia', 'None', 940),
        (240, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 941),
        (240, 'Tool Shop', 'N/A', 'Ginomorsia', 'None', 942),
        (241, 'Combat', 'N/A', 'Treasure Grove', 'Crystal Behemoth', 943),
        (242, 'Material Shop', 'N/A', 'Tropica Isles', 'None', 944),
        (242, 'Combat', 'N/A', 'Depths - B2', 'Black Panther', 945),
        (242, 'Combat', 'N/A', 'Cave of Trials B2', 'Boor Bear Boss', 946),
        (242, 'Combat', 'N/A', 'Depths - B2', 'Cave Panther', 947),
        (243, 'Combat', 'N/A', 'Depths - B3', 'Great Chimera', 948),
        (244, 'Combat', 'N/A', 'Depths - B3', 'Mohawkasaurus', 949),
        (244, 'Combat', 'N/A', 'Treasure Grove', 'Crystal Behemoth', 950),
        (244, 'Combat', 'N/A', 'Treasure Grove', 'Great Gemeleon', 951),
        (245, 'Combat', 'N/A', 'Treasure Grove', 'Gaia Golem', 952),
        (246, 'Crafting', 'Farmer', 'Base Camp', 'Radish', 953),
        (246, 'Crafting', 'Farmer', 'Base Camp', 'Great Spirit Radish', 954),
        (246, 'Combat', 'N/A', 'Cave of Trials', 'Radishella', 955),
        (247, 'Material Shop', 'N/A', 'Eternia Village', 'None', 956),
        (247, 'Material Shop', 'N/A', 'Capital of Mysteria', 'None', 957),
        (247, 'Material Shop', 'N/A', 'Treasure Grove', 'None', 958),
        (248, 'Restaurant', 'N/A', 'Swolean Island', 'None', 959),
        (248, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 960),
        (248, 'Tool Shop', 'N/A', 'Ginomorsia', 'None', 961),
        (249, 'Restaurant', 'N/A', 'Capital of Mysteria', 'None', 962),
        (249, 'Combat', 'N/A', 'Capital of Mysteria', 'White Woolie', 963),
        (249, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 964),
        (249, 'Tool Shop', 'N/A', 'Ginomorsia', 'None', 965),
        (250, 'Restaurant', 'N/A', 'Capital of Mysteria', 'None', 966),
        (250, 'Gathering', 'Angler', 'Capital of Mysteria', 'Small Fish Shadow', 967),
        (251, 'Material Shop', 'N/A', 'Eternia Village', 'None', 968),
        (251, 'Gathering', 'Miner', 'Eternia Village', 'Copper Deposit', 969),
        (251, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 970),
        (251, 'Tool Shop', 'N/A', 'Ginomorsia', 'None', 971),
        (252, 'Restaurant', 'N/A', 'Eternia Village', 'None', 972),
        (252, 'Restaurant', 'N/A', 'Capital of Mysteria', 'None', 973),
        (252, 'Gathering', 'Angler', 'Eternia Village', 'Small Fish Shadow', 974),
        (253, 'Restaurant', 'N/A', 'Capital of Mysteria', 'None', 975),
        (253, 'Gathering', 'Angler', 'Capital of Mysteria', 'Big Fish Shadow', 976),
        (254, 'Material Shop', 'N/A', 'Eternia Village', 'None', 977),
        (254, 'Gathering', 'Miner', 'Eternia Village', 'Copper Deposit', 978),
        (254, 'Gathering', 'Miner', 'Capital of Mysteria', 'Great Copper Deposit', 979),
        (254, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 980),
        (255, 'Material Shop', 'N/A', 'Eternia Village', 'None', 981),
        (255, 'Restaurant', 'N/A', 'Eternia Village', 'None', 982),
        (255, 'Material Shop', 'N/A', 'Eternia Village', 'None', 983),
        (255, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 984),
        (256, 'Material Shop', 'N/A', 'Tropica Isles', 'None', 985),
        (256, 'Combat', 'N/A', 'Depths - B2', 'Star Beetle Baller', 986),
        (256, 'Combat', 'N/A', 'Depths - B2', 'Snow Beetle Baller', 987),
        (256, 'Combat', 'N/A', 'Depths - B3', 'Ancient Beetle Baller', 988),
        (257, 'Restaurant', 'N/A', 'Eternia Village', 'None', 989),
        (257, 'Restaurant', 'N/A', 'Capital of Mysteria', 'None', 990),
        (257, 'Material Shop', 'N/A', 'Treasure Grove', 'None', 991),
        (257, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 992),
        (258, 'Combat', 'N/A', 'Depths - B3', 'Great Chimera', 993),
        (259, 'Combat', 'N/A', 'Cave of Trials B4', 'Napdragon', 994),
        (260, 'Combat', 'N/A', 'Cave of Trials B4', 'Napdragon', 995),
        (261, 'Crafting', 'Farmer', 'Base Camp', 'Giant Mandrake', 996),
        (262, 'Gathering', 'Angler', 'Treasure Grove', 'High-Flying Fish', 997),
        (263, 'Combat', 'N/A', 'Lulab Forest', 'Goldmeer', 998),
        (264, 'Material Shop', 'N/A', 'Eternia Village', 'None', 999),
        (264, 'Woodcutting', 'Woodcutter', 'Eternia Village', 'Oak Tree', 1000),
        (264, 'Combat', 'N/A', 'Lulab Forest', 'Pseudo Oak', 1001),
        (264, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 1002),
        (265, 'Crafting', 'Farmer', 'Base Camp', 'Onion', 1003),
        (265, 'Material Shop', 'N/A', 'Faraway Island', 'None', 1004),
        (265, 'Restaurant', 'N/A', 'Faraway Island', 'None', 1005),
        (266, 'Material Shop', 'N/A', 'Lulab Forest', 'None', 1006),
        (266, 'Crafting', 'Farmer', 'Base Camp', 'Onion', 1007),
        (267, 'Material Shop', 'N/A', 'Eternia Village', 'None', 1008),
        (267, 'Woodcutting', 'Woodcutter', 'Eternia Village', 'Palm Tree', 1009),
        (267, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 1010),
        (267, 'Tool Shop', 'N/A', 'Ginomorsia', 'None', 1011),
        (268, 'Material Shop', 'N/A', 'Eternia Village', 'None', 1012),
        (268, 'Woodcutting', 'Woodcutter', 'Eternia Village', 'Palm Tree', 1013),
        (268, 'Woodcutting', 'Woodcutter', 'Ginomorsia', 'Palm Tree', 1014),
        (268, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 1015),
        (269, 'Material Shop', 'N/A', 'Faraway Island', 'None', 1016),
        (269, 'Combat', 'N/A', 'Faraway Island', 'Peach Bee', 1017),
        (269, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 1018),
        (269, 'Tool Shop', 'N/A', 'Ginomorsia', 'None', 1019),
        (270, 'Material Shop', 'N/A', 'Lulab Forest', 'None', 1020),
        (270, 'Gathering', 'Angler', 'Lulab Forest', 'Small Fish Shadow', 1021),
        (271, 'Material Shop', 'N/A', 'Faraway Island', 'None', 1022),
        (271, 'Woodcutting', 'Woodcutter', 'Faraway Island', 'Pine Tree', 1023),
        (271, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 1024),
        (271, 'Tool Shop', 'N/A', 'Ginomorsia', 'None', 1025),
        (272, 'Material Shop', 'N/A', 'Faraway Island', 'None', 1026),
        (272, 'Woodcutting', 'Woodcutter', 'Faraway Island', 'Pine Tree', 1027),
        (272, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 1028),
        (272, 'Tool Shop', 'N/A', 'Ginomorsia', 'None', 1029),
        (273, 'Material Shop', 'N/A', 'Treasure Grove', 'None', 1030),
        (273, 'Combat', 'N/A', 'Depths - B3', 'Sand Spider', 1031),
        (273, 'Combat', 'N/A', 'Depths - B3', 'Greater Sand Spider', 1032),
        (274, 'Material Shop', 'N/A', 'Swolean Island', 'None', 1033),
        (274, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 1034),
        (275, 'Gathering', 'Angler', 'Capital of Mysteria', 'Plains Lordfish', 1035),
        (275, 'Material Shop', 'N/A', 'Tropica Isles', 'None', 1036),
        (276, 'Gathering', 'Angler', 'Capital of Mysteria', 'Plains Lordfish', 1037),
        (276, 'Material Shop', 'N/A', 'Tropica Isles', 'None', 1038),
        (277, 'Material Shop', 'N/A', 'Swolean Island', 'None', 1039),
        (277, 'Gathering', 'Miner', 'Depths - B2', 'Platinum Deposit', 1040),
        (277, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 1041),
        (277, 'Tool Shop', 'N/A', 'Ginomorsia', 'None', 1042),
        (278, 'Material Shop', 'N/A', 'Capital of Mysteria', 'None', 1043),
        (278, 'Combat', 'N/A', 'Capital of Mysteria', 'Worker Bee', 1044),
        (278, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 1045),
        (278, 'Tool Shop', 'N/A', 'Ginomorsia', 'None', 1046),
        (279, 'Gathering', 'Angler', 'Treasure Grove', 'Poseidon Swordfish', 1047),
        (280, 'Gathering', 'Angler', 'Treasure Grove', 'Poseidon Swordfish', 1048),
        (281, 'Crafting', 'Farmer', 'Base Camp', 'Potato', 1049),
        (281, 'Crafting', 'Farmer', 'Base Camp', 'Spooky Spud', 1050),
        (281, 'Material Shop', 'N/A', 'Faraway Island', 'None', 1051),
        (281, 'Restaurant', 'N/A', 'Faraway Island', 'None', 1052),
        (282, 'Restaurant', 'N/A', 'Tropica Isles', 'None', 1053),
        (282, 'Material Shop', 'N/A', 'Treasure Grove', 'None', 1054),
        (282, 'Combat', 'N/A', 'Ginomorsia', 'Burly Gorilla', 1055),
        (282, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 1056),
        (283, 'Restaurant', 'N/A', 'Capital of Mysteria', 'None', 1057),
        (283, 'Combat', 'N/A', 'Capital of Mysteria', 'Worker Bee', 1058),
        (283, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 1059),
        (284, 'Material Shop', 'N/A', 'Eternia Village', 'None', 1060),
        (284, 'Material Shop', 'N/A', 'Tropica Isles', 'None', 1061),
        (284, 'Combat', 'N/A', 'Tropica Isles', 'Bitey Shark', 1062),
        (284, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 1063),
        (285, 'Restaurant', 'N/A', 'Capital of Mysteria', 'None', 1064),
        (285, 'Gathering', 'Angler', 'Base Camp', 'Small Fish Shadow', 1065),
        (286, 'Crafting', 'Farmer', 'Base Camp', 'Pumpkin', 1066),
        (286, 'Crafting', 'Farmer', 'Base Camp', 'Kaiser Pumpkin', 1067),
        (286, 'Material Shop', 'N/A', 'Faraway Island', 'None', 1068),
        (286, 'Restaurant', 'N/A', 'Faraway Island', 'None', 1069),
        (287, 'Material Shop', 'N/A', 'Faraway Island', 'None', 1070),
        (287, 'Material Shop', 'N/A', 'Faraway Island', 'None', 1071),
        (287, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 1072),
        (287, 'Material Shop', 'N/A', 'Treasure Grove', 'None', 1073),
        (288, 'Crafting', 'Farmer', 'Base Camp', 'Cabbage', 1074),
        (288, 'Crafting', 'Farmer', 'Base Camp', 'Godly Cabbage', 1075),
        (288, 'Material Shop', 'N/A', 'Lulab Forest', 'None', 1076),
        (289, 'Material Shop', 'N/A', 'Tropica Isles', 'None', 1077),
        (289, 'Gathering', 'Miner', 'Profunda Cave', 'Superior Marine Ore Deposit', 1078),
        (289, 'Combat', 'N/A', 'Treasure Grove', 'Gemeleon', 1079),
        (289, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 1080),
        (290, 'Combat', 'N/A', 'Faraway Island', 'Giant Grass Serpent', 1081),
        (290, 'Combat', 'N/A', 'Depths - B3', 'King Cobra', 1082),
        (291, 'Material Shop', 'N/A', 'Tropica Isles', 'None', 1083),
        (291, 'Gathering', 'Miner', 'Tropica Isles', 'Silver Ore Deposit', 1084),
        (291, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 1085),
        (291, 'Tool Shop', 'N/A', 'Ginomorsia', 'None', 1086),
        (292, 'Gathering', 'Angler', 'Depths - B3', 'Small Fish Shadow', 1087),
        (293, 'Restaurant', 'N/A', 'Swolean Island', 'None', 1088),
        (293, 'Material Shop', 'N/A', 'Cave of Trials B3', 'None', 1089),
        (293, 'Combat', 'N/A', 'Depths - B2', 'Crimson Razorbeak', 1090),
        (293, 'Combat', 'N/A', 'Treasure Grove', 'Tunoco Quetzal', 1091),
        (294, 'Combat', 'N/A', 'Capital of Mysteria', 'Tunoco Quetzal', 1092),
        (295, 'Combat', 'N/A', 'Capital of Mysteria', 'Tunoco Quetzal', 1093),
        (296, 'Crafting', 'Farmer', 'Base Camp', 'Radish', 1094),
        (296, 'Crafting', 'Farmer', 'Base Camp', 'Great Spirit Radish', 1095),
        (296, 'Material Shop', 'N/A', 'Faraway Island', 'None', 1096),
        (296, 'Combat', 'N/A', 'Spirit Road', 'Radishy', 1097),
        (297, 'Material Shop', 'N/A', 'Tropica Isles', 'None', 1098),
        (297, 'Combat', 'N/A', 'Spirit Road', 'Radishy', 1099),
        (297, 'Combat', 'N/A', 'Cave of Trials', 'Radishella', 1100),
        (297, 'Combat', 'N/A', 'Depths - B2', 'Frosty Radishy', 1101),
        (298, 'Crafting', 'Farmer', 'Base Camp', 'Radish', 1102),
        (298, 'Crafting', 'Farmer', 'Base Camp', 'Great Spirit Radish', 1103),
        (298, 'Material Shop', 'N/A', 'Lulab Forest', 'None', 1104),
        (298, 'Combat', 'N/A', 'Cave of Trials', 'Radishy', 1105),
        (299, 'Combat', 'N/A', 'Treasure Grove', 'Bigbeak', 1106),
        (300, 'Gathering', 'Angler', 'Swolean Island', 'Rainbow Flying Fish', 1107),
        (301, 'Gathering', 'Angler', 'Swolean Island', 'Rainbow Flying Fish', 1108),
        (302, 'Material Shop', 'N/A', 'Eternia Village', 'None', 1109),
        (302, 'Material Shop', 'N/A', 'Eternia Village', 'None', 1110),
        (302, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 1111),
        (302, 'Tool Shop', 'N/A', 'Ginomorsia', 'None', 1112),
        (303, 'Material Shop', 'N/A', 'Tropica Isles', 'None', 1113),
        (303, 'Combat', 'N/A', 'Depths - B2', 'Splash Frog', 1114),
        (304, 'Restaurant', 'N/A', 'Tropica Isles', 'None', 1115),
        (304, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 1116),
        (304, 'Tool Shop', 'N/A', 'Ginomorsia', 'None', 1117),
        (305, 'Material Shop', 'N/A', 'Swolean Island', 'None', 1118),
        (305, 'Combat', 'N/A', 'Cave of Trials', 'Rock Serpent', 1119),
        (305, 'Combat', 'N/A', 'Cave of Trials', 'Greater Rock Serpent', 1120),
        (306, 'Gathering', 'Angler', 'Ginomorsia', 'Small Fish Shadow', 1121),
        (307, 'Material Shop', 'N/A', 'Eternia Village', 'None', 1122),
        (307, 'Woodcutting', 'Woodcutter', 'Eternia Village', 'Palm Tree', 1123),
        (307, 'Woodcutting', 'Woodcutter', 'Ginomorsia', 'Palm Tree', 1124),
        (307, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 1125),
        (308, 'Material Shop', 'N/A', 'Lulab Forest', 'None', 1126),
        (308, 'Combat', 'N/A', 'Lulab Forest', 'Killer Bear', 1127),
        (308, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 1128),
        (309, 'Material Shop', 'N/A', 'Lulab Forest', 'None', 1129),
        (309, 'Combat', 'N/A', 'Da Finci Cave', 'Umbral Runner', 1130),
        (309, 'Combat', 'N/A', 'Da Finci Cave', 'White Runner', 1131),
        (309, 'Material Shop', 'N/A', 'Spirit Road', 'None', 1132),
        (310, 'Gathering', 'Miner', 'Depths - B2', 'Superior Red Ore Deposit', 1133),
        (310, 'Gathering', 'Miner', 'Depths - B3', 'Dragon''s Claw', 1134),
        (310, 'Combat', 'N/A', 'Treasure Grove', 'Great Gemeleon', 1135),
        (311, 'Material Shop', 'N/A', 'Eternia Village', 'None', 1136),
        (311, 'Material Shop', 'N/A', 'Capital of Mysteria', 'None', 1137),
        (311, 'Material Shop', 'N/A', 'Capital of Mysteria', 'None', 1138),
        (311, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 1139),
        (312, 'Material Shop', 'N/A', 'Treasure Grove', 'None', 1140),
        (312, 'Combat', 'N/A', 'Spirit Road', 'Mimic', 1141),
        (312, 'Combat', 'N/A', 'Depths - B3', 'Pandora''s Box', 1142),
        (313, 'Material Shop', 'N/A', 'Treasure Grove', 'None', 1143),
        (313, 'Combat', 'N/A', 'Spirit Road', 'Mimic', 1144),
        (313, 'Combat', 'N/A', 'Depths - B3', 'Pandora''s Box', 1145),
        (314, 'Material Shop', 'N/A', 'Ginomorsia', 'None', 1146),
        (314, 'Combat', 'N/A', 'Spirit Road', 'Mimic', 1147),
        (314, 'Combat', 'N/A', 'Depths - B3', 'Pandora''s Box', 1148),
        (315, 'Restaurant', 'N/A', 'Eternia Village', 'None', 1149),
        (315, 'Restaurant', 'N/A', 'Capital of Mysteria', 'None', 1150),
        (315, 'Marco''s Shop', 'N/A', 'Base Camp', 'None', 1151),
        (315, 'Tool Shop', 'N/A', 'Ginomorsia', 'None', 1152),
        (316, 'Gathering', 'Angler', 'Ginomorsia', 'Small Fish Shadow', 1153),
        (317, 'Material Shop', 'N/A', 'Swolean Island', 'None', 1154),
        (317, 'Gathering', 'Miner', 'Cave of Trials', 'Gold Deposit', 1155),
        (317, 'Combat', 'N/A', 'Depths - B3', 'Sand Golem', 1156),
        (317, 'Tool Shop', 'N/A', 'Ginomorsia', 'None', 1157),
        (318, 'Gathering', 'Miner', 'Depths - B2', 'Platinum Deposit', 1158),
        (318, 'Gathering', 'Miner', 'Depths - B2', 'Great Platinum Deposit', 1159),
        (318, 'Combat', 'N/A', 'Treasure Grove', 'Great Gemeleon', 1160),
        (319, 'Restaurant', 'N/A', 'Eternia Village', 'None', 1161),
        (319, 'Restaurant', 'N/A', 'Capital of Mysteria', 'None', 1162),
        (319, 'Gathering', 'Angler', 'Base Camp', 'Small Fish Shadow', 1163);