import {
   Typography,
   Box,
   Tooltip,
   IconButton,
   ToggleButton,
   ToggleButtonGroup,
} from "@mui/material";
import InfoOutlinedIcon from "@mui/icons-material/InfoOutlined";

// Data import
import bisCategories from "../../../../data/bisConfig";

// Import shared styles
import { toggleStyles, tabPanelBoxStyles } from '../../../../shared-logic/presetStyles';

const BiSTab = ({ selectedBiSCategories, onBiSCategoriesChange }) => {
   return (
      <Box sx={tabPanelBoxStyles}>
         <Box
            display="flex"
            alignItems="center"
            justifyContent="center"
            gap={0.5}
            mb={0.5}
         >
            <Tooltip
               title="The recipes generated by this preset are based on community consensus and subject to change. Please provide feedback in the dev discord if the information is incorrect or outdated."
               arrow
            >
               <IconButton
                  size="small"
                  sx={{
                     p: 0,
                     color: "text.secondary",
                     backgroundColor: "#fff",
                  }}
               >
                  <InfoOutlinedIcon fontSize="small" />
               </IconButton>
            </Tooltip>
            <Typography variant="h6">
               Best in Slot Categories:
            </Typography>
         </Box>

         <ToggleButtonGroup
            orientation="vertical"
            value={selectedBiSCategories}
            onChange={(_, newSelection) =>
               onBiSCategoriesChange(newSelection)
            }
            sx={{
               width: "100%",
               "& .MuiToggleButtonGroup-grouped": {
                  border: "none",
                  borderRadius: 2,
               },
            }}
         >
            {["General", "Tools", "Armor", "Weapons"].map(
               (groupName) => (
                  <Box key={groupName} mt={1.5}>
                     <Typography variant="subtitle1" gutterBottom>
                        {groupName}
                     </Typography>
                     <Box
                        display="flex"
                        justifyContent="center"
                        flexWrap="wrap"
                     >
                        {bisCategories
                           .filter((cat) => cat.group === groupName)
                           .map((cat) => (
                              <ToggleButton
                                 key={cat.id}
                                 value={cat.id}
                                 sx={toggleStyles}
                              >
                                 {cat.label}
                              </ToggleButton>
                           ))}
                     </Box>
                  </Box>
               )
            )}
         </ToggleButtonGroup>
      </Box>
   );
};

export default BiSTab;